### ISSUE TITLE
GPL-353	As Development team (LIMS) we want to create a table in the MLWH to link supplier sample id for heron samples to CGAp released Tube and tube rack to pass this id to genomics pipeline

### ISSUE THREAD

**Issue by rl15** [sanger/unified_warehouse#102]

**Comment by stevieing** [comment]
1. Generate migration for ??? table with the following columns:
- Tube rack barcode (String) e.g. DN1234567
- Tube barcode (String) unique e.g. FD123456
- Supplier Sample ID (String) unique e.g. PHEC-nnnnnnnnnnnnnn
- Position (String) e.g. A11

**Comment by pjvv** [comment]
Done by CGaP
