### ISSUE TITLE
GPL-382 Add study_samples table from SS into MLWH

### ISSUE THREAD

**Issue by rl15** [sanger/unified_warehouse#105]
**User story**
GPL-382 As a report writer (Matt Francis) I would like to be able the use the information in thestudy_samples table that is in SS to be able to easily identify samples thatbelong to a particular study, in this case Heron. This would enable us toeasily identify flowcells, runs etc for Heron Samples. This requires that thestudy_sample table be available in the MLWH

**Who the primary contacts are for this story**
Matt Francis
Neil Sycamore

**Acceptance criteria**
To be considered successful the solution must allow:
1. add a list of acceptance criteria here
2. ...

**Additional context**

**Comment by JamesGlover** [comment]
Issues:
1) As per the comment on 'StudySample' itself
> This association is probably a little unreliable, and should not be relied upon for critical behaviour.
2) This is because the study on aliquot is now the primary way in which work is being associated with a particular study. This information is already exposed in the warehouse in the flowcell tables themselves. (Is there a reason this existing information isn't suitable?)
3) I'm not sure if we reliably create a study-sample link every time work is performed on a sample under a new study. Relying on this table may miss work.
4) As a sample can belong to multiple studies, relying on this table would find the same samples sequenced under different studies.

**Comment by rl15** [comment]
What other options do we have to help improve the situation for Matt?

**Comment by KatyTaylor** [comment]
@rl15 - do you know why the existing link from the flow cell table in the MLWH isn't suitable (as mentioned by James)? 
iseq_flowcell table, column called id_study_tmp, which links to study table

**Comment by rl15** [comment]
On 09/04/2020, 10:24, "Matt Francis" <mdf@sanger.ac.uk> wrote:
        
            No I guess not actually.
            
            select distinct sample.supplier_name from study
            join iseq_flowcell on study.id_study_tmp = iseq_flowcell.id_study_tmp
            join sample on iseq_flowcell.id_sample_tmp = sample.id_sample_tmp
            where study.name like 'Heron Project';
            
            Pulls out 1119 samples, which have been sequenced (they appear on a flowcell) And given that all samples sent from CGAP are going to be sequenced then everything should eventually end up on a flowcell.
            
            The only issue with this query at the moment is where you have the first lot of R&D mixed in with the others. But that’s only a major issue now as the proportion is significant, when we ramp up that number will be tiny so will not be so visible.
            
            Ok, drop that story as there is sufficient information that we can get some good numbers out. I'll make sure I define and record where the numbers are coming from so everyone knows what tables and processes are being used.
            
            The one thing that is really useful, I spoke to Neil about this, is having a way to idenfity in the sample table in MLWH if the sample entered via CGAP or direct to SS. From your mail yesterday the bulk samples are going to arrive with manifests, which I don't think is exposed in the warehouse? If we have a way of identifying those samples that came in via the non-cgap route we can add that to the reporting to have the correct Sample Arrival counts.
            
            I could do it by some nasty NOT IN(select samplename from cgap_heron) but would be a nicer fix if the sample table had the manifest ID or something similar then we can say
            
            If sample has a manifest it came direct to SS
            If sample is in cgap_heron it came to cgap
            
            And that way their shouldn’t be any sample that’s in both lists.

**Comment by rl15** [comment]
On 09/04/2020, 15:28, "Rich Livett" <rl15@sanger.ac.uk> wrote:
    
        Matt
        
        Thanks for prompt response. Have updated the backlog item in git to keep the record in one place;
        
        > The one thing that is really useful, I spoke to Neil about this, is having a way to idenfity in the sample table in MLWH if the sample entered via CGAP or direct to SS. From your mail yesterday the bulk samples are going to arrive with manifests, which I don't think is exposed in the warehouse? If we have a way of identifying those samples that came in via the non-cgap route we can add that to the reporting to have the correct Sample Arrival counts.
        
        Is potentially a bit fragile but all plates with nucleotides will come direct to Genomics pipelines.
        To date these plated nucleotides are going to come from
        
        UK Bioenter with COG-UK barcodes starting with MILK
        And where it gets fragile *some* of the consortium expecting plates from National Infection Service, Public Health England COG-UK barcodes starting with PHEC
        (https://ssg-confluence.internal.sanger.ac.uk/x/vZYKBg)
        
        The COG-UK barcodes are being entered in the  Supplier_Sample_Name  or all (or should be)
        
        NB Just peeped at report looking great - nice iteration.

**Comment by rl15** [comment]
can certainly use the barcode prefixes to denote the origin, and then by assumption if its plates or tubes, and therefore SS or CGAP origin.
    
    AS this is a moving thing anyway its cheap enough for me to create the dashboard using those rules once the data arrives, and then modifiy/refine/throwaway if it does fall over or we have a more robust way of counting/categorising.

 All of your people are doing a great job, the combination of a fast evolving project, lots of unknowns, co-ordinating different teams would be hard enough on a normal Sanger day, but to do it all remotely with all the other family/household distractions is quite remarkable.

**Comment by rl15** [comment]
Matt Francis <mdf@sanger.ac.uk> wrote
Wednesday, 15 April 2020 at 16:49

Ok will keep doing it this way and document the report.

Deprecate away
