### ISSUE TITLE
Fluidigm experiment status

### ISSUE THREAD

**Issue by keithj** [sanger/unified_warehouse#11]
If rows appear in the Fluidigm (flgen_plate) table before the experiment has been done, a column describing progress would be valuable i.e. a controlled vocabulary term to indicate whether the experiment was pending or complete (or whether the status is unknown).

**Comment by JamesGlover** [comment]
Currently we can detect the following states:
1) The fludigm plate has been produced in the Lims and is available for testing. It may or may not have been tested.
2) We have found a file in irods, corresponding to the plate.

Additional difficulties:
1) Genotyping data is stored on the stock plate. If a stock plate is subject to fluidigm treatment multiple times, it is not currently possible to tell which plates are completed.
