### ISSUE TITLE
GPL-620 Example query for 'LHR RT' and 'LHR-384' plate purposes Library start date for PAM

### ISSUE THREAD

**Issue by rl15** [sanger/unified_warehouse#119]
**Description**
GPL-620 | As reporting lead for PAM (Rob K) I would like an example SQL query for MLWH giving the date of "Library Prep" which is associated with the 'LHR RT' and 'LHR-384' plate purposes to understand library start for Heron

**Who the primary contacts are for this work**
Tom W (Did initial work and meetings in early mid Aug)
Rob K
Neil S

**Additional context or information**
Request in RT https://rt.sanger.ac.uk/Ticket/Display.html?id=697159
See current state of art in https://ssg-confluence.internal.sanger.ac.uk/x/u5kKBg
Example SQL in section 4.2.4, Give me all the COG-UK samples that have been made into library's (G.7)

**Comment by rl15** [comment]
NB With move to new '384 Heron tailed workflow' will *still* use LHR RT (IJ, 26th Aug)  - Project 15:00 meeting

**Comment by JamesGlover** [comment]
If the library start events are missing, then this is a bug we shall need to fix up. This should be reasonably simple, and in the past its been possible to back-populate the data. This will allow the events warehouse to be used as intended.

**Comment by JamesGlover** [comment]
Double checked events against the submission to confirm that were not just missing the events because we are looking for the wrong subject.

**Comment by JamesGlover** [comment]
So definitely going to need to get library start in there to improve on the existing query.

**Comment by JamesGlover** [comment]
Previously the library start event was handled by the PlatePurpose::Initial module, which was included in the initial plate purpose class. This was traditionally the one immediately downstream of the input plate (ie. the first plate created as part of the pipeline).

In limber we eliminated a lot of the custom plate classes, to allow for easy reconfiguration, and a flexible route through. For example, even if we had used a purpose with 'Initial' included, this would have fallen apart the moment someone deviated from the expected route.

**Comment by JamesGlover** [comment]
This means library start events are going to be missing for most Limber plates. We'll need to restore the behaviour. This probably means adding similar behaviour to the standard PlatePurpose. Need to be wary of performance though.

**Comment by JamesGlover** [comment]
Oddly 'PF Shear' is an initial plate, so a handful of limber plates will have the correct events.

**Comment by JamesGlover** [comment]
Running into a lot of legacy classes when investigating this. Might be time to kill them

**Comment by JamesGlover** [comment]
================================================================================
Tube::Purpose
--------------------------------------------------------------------------------
Used (direct): 7
Used (subclasses): 26
Last used (direct): 2020-09-01 15:29:27 +0100
Last used (subclasses): 2020-09-02 14:08:33 +0100
--------------------------------------------------------------------------------
Purposes using this class directly:
Standard sample
Standard library
Stock library
saphyr
PhiX Spiked Buffer
PhiX Stock
long_read
================================================================================
PlatePurpose
--------------------------------------------------------------------------------
Used (direct): 191
Used (subclasses): 57
Last used (direct): 2020-09-02 15:33:16 +0100
Last used (subclasses): 2020-09-02 15:25:04 +0100
--------------------------------------------------------------------------------
Purposes using this class directly:
Stock Plate
40ng
Whole Genome Amplification
Sequenom
Gel Dilution
Pico Assay A
Normalisation
Infinium_610K
Pico Standard
Affymetrix_SNP6
Infinium 670k
Methylation
ImmunoChip
OMNI 1
OMNI EXPRESS
Pulldown
Omnichip_Express
Pico Assay Plates
Pico Assay B
Gel Dilution Plates
Pulldown Aliquot
Infinium 2.5M
aCGH
Cherrypicked Working Dilution
CGP
DDD OMNI
SEQCAP WG
SEQCAP SC
Aliquot 1
Aliquot 2
Aliquot 3
Aliquot 4
OMNI2.5M-8
WGS post-Cov
WGS post-Cov-XP
WGS lib
WGS lib PCR-XP
WGS lib pool
SC post-Cov
SC post-Cov-XP
SC lib
SC lib PCR
SC lib PCR-XP
SC hyb
SC cap lib
SC cap lib PCR-XP
SC cap lib pool
ISC post-Cov
ISC post-Cov-XP
ISC lib
ISC lib PCR-XP
ISC lib pool
ISC hyb
ISC cap lib
ISC cap lib PCR
ISC cap lib PCR-XP
ISC cap lib pool
Pulldown QC plate
OMNI 5M
Fake Stock Plate
Exome Chip
Exome Chip Extra
Illumina B test
ILB_STD_SH
ILB_STD_PREPCR
ILB_STD_PCR
ILB_STD_PCRR
Human Core Exome
Fluidigm
Illumina GEX - Hu12v4
Post Shear
AL Libs
Lib PCR
Lib PCRR
Lib PCR-XP QC
Lib PCRR-XP QC
Stock RNA Plate
Post Shear XP
RNASEQ
STA
STA2
Fluidigm 96-96
Fluidigm 192-24
SNP Type
PacBio Sheared
Pacbio
Tag PCR-XP
Strip Tube Purpose
Lib Norm QC
PacBio Sequencing
Quant STD
MEGAarray
Pre-Extracted Plate
PF Post Shear
PF Post Shear XP
PF Lib
PF Lib XP
PF Lib XP2
PF EM Pool
PF EM Pool QC
QA Plate
Chromium quant
LB Shear
LB Post Shear
LB End Prep
LB Lib PCR
LB Lib PCR-XP
LB Lib PrePool
LB Hyb
LB Cap Lib
LB Cap Lib PCR
LB Cap Lib PCR-XP
LB Cap Lib Pool
SWGA Stock
GridION
Omni2.5-8Exome
PF End Prep
LBR mRNA Cap
LBR Frag
LB cDNA
LB cDNA XP
scRNA cDNA-XP
scRNA End Prep
scRNA Lib PCR
GBS PCR1
GBS PCR2
LBR Globin
LBR Globin DNase
LBR Frag cDNA
scRNA-384 cDNA-XP
scRNA-384 End Prep
scRNA-384 Lib PCR
LBR Ribo DNase
LBR RiboGlobin DNase
GnT scDNA
GnT Pico-XP
GnT Pico End Prep
GnT Pico Lib PCR
GnT MDA Norm
PF-384 Post Shear XP
PF-384 End Prep
PF-384 Lib
PF-384 Lib XP2
PF Lib Q-XP2
LBB Ligation
LBB Lib PCR
LBB Lib PCR-XP
LBB Ligation Tagged
LBB Lib-XP
LBB Chromium Tagged
LBC Aggregate
LBC Cherrypick
LBC 3pV3 GEX Dil
LBC 3pV3 GEX Frag 2XP
LBC 3pV3 GEX LigXP
LBC 3pV3 GEX PCR 2XP
LBC 5p GEX Dil
LBC 5p GEX Frag 2XP
LBC 5p GEX LigXP
LBC 5p GEX PCR 2XP
LBC TCR Dil 1
LBC BCR Dil 1
LBC TCR Enrich1 1XSPRI
LBC TCR Enrich2 2XSPRI
LBC TCR Dil 2
LBC TCR Post Lig 1XSPRI
LBC TCR Post PCR
LBC BCR Enrich1 1XSPRI
LBC BCR Enrich2 2XSPRI
LBC BCR Dil 2
LBC BCR Post Lig 1XSPRI
LBC BCR Post PCR
LHR Stock
LHR XP
LHR End Prep
LHR Lib PCR
LDS Stock XP
LDS AL Lib
LDS AL Lib Dil
LDS Lib PCR
LDS Lib PCR XP
LHR PCR 1
LHR PCR 2
LHR-384 PCR 1
LHR-384 PCR 2
LHR-384 cDNA
LHR-384 XP
LHR-384 End Prep
LHR-384 AL Lib
LHR-384 Lib PCR
LHR Cherrypick
================================================================================
TubeRack::Purpose
--------------------------------------------------------------------------------
Used (direct): 3
Used (subclasses): 0
Last used (direct): 2020-08-03 09:12:32 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
TR Stock 96
TR Stock 48
Heron Lysed Tube Rack
================================================================================
QcableTubePurpose
--------------------------------------------------------------------------------
Used (direct): 1
Used (subclasses): 0
Last used (direct): 2018-06-18 11:38:56 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
Tag 2 Tube
================================================================================
IlluminaC::QcPoolPurpose
--------------------------------------------------------------------------------
Used (direct): 3
Used (subclasses): 0
Last used (direct): 2017-08-02 14:36:05 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
ILC QC Pool
PF MiSeq QC
PF MiSeq QCR
================================================================================
IlluminaHtp::MxTubePurpose
--------------------------------------------------------------------------------
Used (direct): 2
Used (subclasses): 8
Last used (direct): 2017-04-28 14:16:03 +0100
Last used (subclasses): 2020-09-02 14:08:33 +0100
--------------------------------------------------------------------------------
Purposes using this class directly:
Lib Pool Norm
Lib Pool SS-XP-Norm
================================================================================
IlluminaHtp::StockTubePurpose
--------------------------------------------------------------------------------
Used (direct): 8
Used (subclasses): 0
Last used (direct): 2020-03-10 08:59:22 +0000
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
ILB_STD_STOCK
Lib Pool Conc
Lib Pool SS
Lib Pool SS-XP
PF MiSeq Stock
GBS PCR2 Pool Stock
GBS PCR Pool
GBS PCR Pool Selected
================================================================================
Tube::StandardMx
--------------------------------------------------------------------------------
Used (direct): 2
Used (subclasses): 0
Last used (direct): 2020-09-01 16:24:31 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
Standard MX
Tag MX
================================================================================
Tube::StockMx
--------------------------------------------------------------------------------
Used (direct): 2
Used (subclasses): 0
Last used (direct): 2020-09-01 16:24:31 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
Stock MX
Tag Stock-MX
================================================================================
IlluminaC::MxTubePurpose
--------------------------------------------------------------------------------
Used (direct): 1
Used (subclasses): 0
Last used (direct): 2019-05-21 09:05:09 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
ILC Lib Pool Norm
================================================================================
IlluminaB::MxTubePurpose
--------------------------------------------------------------------------------
Used (direct): 1
Used (subclasses): 0
Last used (direct): 2014-06-20 10:47:49 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
ILB_STD_MX
================================================================================
IlluminaHtp::MxTubeNoQcPurpose
--------------------------------------------------------------------------------
Used (direct): 6
Used (subclasses): 0
Last used (direct): 2020-09-02 14:08:33 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
Cap Lib Pool Norm
Legacy MX tube
LB Lib Pool Norm
scRNA Lib Pool Norm
GBS MiSeq Pool
GnT Pico Lib Pool Norm
================================================================================
DilutionPlatePurpose
--------------------------------------------------------------------------------
Used (direct): 4
Used (subclasses): 0
Last used (direct): 2020-08-03 08:58:56 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
Working Dilution
Pico Dilution
Dilution Plates
RNA Working Dilution
================================================================================
PlatePurpose::Input
--------------------------------------------------------------------------------
Used (direct): 20
Used (subclasses): 0
Last used (direct): 2020-09-02 15:25:04 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
WGS stock DNA
SC stock DNA
ISC stock DNA
ILB_STD_INPUT
Cherrypicked
PF Cherrypicked
LB Cherrypick
LBR Cherrypick
scRNA Stock
GBS Stock
scRNA-384 Stock
GnT Stock
GBS-96 Stock
LBB Cherrypick
LBC Stock
LDS Stock
LDS Cherrypick
LHR RT
LHR-384 RT
Heron Lysed Plate
================================================================================
QcableLibraryPlatePurpose
--------------------------------------------------------------------------------
Used (direct): 1
Used (subclasses): 0
Last used (direct): 2018-08-13 14:58:23 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
Tag PCR
================================================================================
QcablePlatePurpose
--------------------------------------------------------------------------------
Used (direct): 4
Used (subclasses): 0
Last used (direct): 2020-08-27 13:54:30 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
Tag Plate
Reporter Plate
Pre Stamped Tag Plate
Tag Plate - 384
================================================================================
IlluminaC::AlLibsTaggedPurpose
--------------------------------------------------------------------------------
Used (direct): 2
Used (subclasses): 0
Last used (direct): 2019-05-21 13:45:15 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
ILC AL Libs Tagged
ILC Lib Chromium
================================================================================
IlluminaC::LibPcrPurpose
--------------------------------------------------------------------------------
Used (direct): 1
Used (subclasses): 0
Last used (direct): 2019-03-27 11:33:23 +0000
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
ILC Lib PCR
================================================================================
IlluminaC::LibPcrXpPurpose
--------------------------------------------------------------------------------
Used (direct): 1
Used (subclasses): 0
Last used (direct): 2019-03-27 11:37:12 +0000
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
ILC Lib PCR-XP
================================================================================
IlluminaC::StockPurpose
--------------------------------------------------------------------------------
Used (direct): 1
Used (subclasses): 0
Last used (direct): 2019-05-21 08:19:28 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
ILC Stock
================================================================================
IlluminaHtp::DownstreamPlatePurpose
--------------------------------------------------------------------------------
Used (direct): 5
Used (subclasses): 0
Last used (direct): 2017-07-03 10:09:17 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
ISCH hyb
ISCH cap lib
ISCH cap lib PCR
ISCH cap lib PCR-XP
ISCH cap lib pool
================================================================================
IlluminaHtp::FinalPlatePurpose
--------------------------------------------------------------------------------
Used (direct): 2
Used (subclasses): 2
Last used (direct): 2014-06-29 08:08:58 +0100
Last used (subclasses): 2018-03-21 14:39:18 +0000
--------------------------------------------------------------------------------
Purposes using this class directly:
ILB_STD_PCRXP
ILB_STD_PCRRXP
================================================================================
IlluminaHtp::LibraryCompleteOnQcPurpose
--------------------------------------------------------------------------------
Used (direct): 0
Used (subclasses): 0
Last used (direct):
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
================================================================================
IlluminaHtp::NormalizedPlatePurpose
--------------------------------------------------------------------------------
Used (direct): 1
Used (subclasses): 0
Last used (direct): 2017-03-23 11:25:17 +0000
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
Lib Norm 2
================================================================================
IlluminaHtp::PooledPlatePurpose
--------------------------------------------------------------------------------
Used (direct): 2
Used (subclasses): 0
Last used (direct): 2017-06-22 16:01:45 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
Lib Norm 2 Pool
PF Lib Norm
================================================================================
IlluminaHtp::PostShearQcPlatePurpose
--------------------------------------------------------------------------------
Used (direct): 1
Used (subclasses): 0
Last used (direct): 2014-11-04 14:08:50 +0000
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
Post Shear QC
================================================================================
PlatePurpose::InitialPurpose
--------------------------------------------------------------------------------
Used (direct): 4
Used (subclasses): 0
Last used (direct): 2020-08-24 10:58:06 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
ILB_STD_COVARIS
Shear
ILC AL Libs
PF Shear
================================================================================
Pulldown::InitialPlatePurpose
--------------------------------------------------------------------------------
Used (direct): 3
Used (subclasses): 0
Last used (direct): 2014-06-19 07:50:46 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
WGS Covaris
SC Covaris
ISC Covaris
================================================================================
Pulldown::LibraryPlatePurpose
--------------------------------------------------------------------------------
Used (direct): 3
Used (subclasses): 0
Last used (direct): 2014-07-29 08:01:17 +0100
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
WGS lib PCR
SC cap lib PCR
ISC lib PCR
================================================================================
IlluminaHtp::TransferablePlatePurpose
--------------------------------------------------------------------------------
Used (direct): 2
Used (subclasses): 0
Last used (direct): 2018-03-21 14:39:18 +0000
Last used (subclasses):
--------------------------------------------------------------------------------
Purposes using this class directly:
Lib PCR-XP
Lib PCRR-XP

**Comment by JamesGlover** [comment]
### Backfilling data

Instructions for backfilling data
1. Merge in changes and roll release
2. Deploy Sequencescape
3. ssh onto sequencescape production servers

```
$ tmux
$ cd /var/www/sequencescape/current
$ export DEPLOY_DATE='04/09/2020' # Sets to date of deployment.
$ bundle exec rake support:back_fill_library_start_events
```
4. Wait for the rake task to complete. It may take a while.
5. If the VPN fails, ssh onto the server again and type
```
tmux attach
```
6. This will restore the connection

**Comment by KatyTaylor** [comment]
Thanks James. Did you check that that format of date gets parsed correctly or is that just an example?

**Comment by JamesGlover** [comment]
It gets parse correctly, I checked

**Comment by JamesGlover** [comment]
Running into some performance issues with the integration suite. It seems to be mostly related to transfer collections, which shouldn't be affected by my changes (And aren't loading request metadata). Think its mostly a case of VPN bandwith and latency pushing already slow behaviour over the edge.

**Comment by JamesGlover** [comment]
Battled to increase timeouts, and also looking at low-0hanging fruit performance increases. Turns out there was some request metadata being loaded there, but we also weren't loading requests as efficiently as we could. Also, weirdly, loading in plate purposes, which I don't quite understand.

**Comment by JamesGlover** [comment]
Nope. This isn't right. Finally got integration suite working, and we're sending nonsense to BroadcastEvent

**Comment by JamesGlover** [comment]
Fixed the nonsense, still got terrible performance, although the broadcast events themselves are taking only about 400ms of database time. (Haven't checked the ruby time, but there's not much going on there) Going to fix up a bit of the eager loading here, but then push to UAT and test things there as dev mode can introduce lots of performance issues, and connecting to the database over the VPN can't be helping)

**Comment by JamesGlover** [comment]
Phew, deployed on UAT and everything running snappily. So either the VPN causing pain, or development mode in general.
Looking good so far.

**Comment by JamesGlover** [comment]
Hmm, seems that logs don't go to the console by default. You can SSH onto the server in a seperate terminal (Or split yout tmux window if you know how) and run:

```
tail -f /var/log/syslog | grep sequencescape[rake_task_pid]
```
To get the logs.

You can find the rake task pis with 
```
ps aux | grep rake
```

I'm sure some fancy use of awk or sed could get things neater, but my skills there are sadly lacking, and its Saturday and I just want to get this handed over.
