### ISSUE TITLE
GPL-660 Migrate historical COG UK ids to lighthouse_sample

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/unified_warehouse#125]
**User story**
This is a hangover task from [GPL-579](https://github.com/sanger/unified_warehouse/issues/118).
Splitting it out as it is taking longer, and the rest of the story has been deployed to production already.
Our migration we wrote was prohibitively slow when run on prod, so we need to improve it.

Problem is lack of indexes for fields used in joining the lighthouse_sample, sample and stock resource tables.
So queries are table scanning 3 large tables to process the update.

Possible solution is to make indexes temporarily (see comments below).

**Who are the primary contacts for this story**
Andrew, Katy

**Comment by KatyTaylor** [comment]
Analysis on mlwhd_mlwarehouse_devdata:
```
SELECT Count(Id)
FROM lighthouse_sample ls;
-- 2,676,937

SELECT Count(DISTINCT root_sample_id)
FROM lighthouse_sample ls;
-- 2,675,871

SELECT * 
FROM (
  SELECT Count(Id) as 'num', root_sample_id
  FROM lighthouse_sample ls
  GROUP BY root_sample_id
) AS grouped
WHERE grouped.num > 1
-- 1,064
```

Suggestion - update first JUST joining based on lighthouse_sample.root_sample_id = sample.description
Then update the ~1000 that appear more than once based on root sample id with the more complicated matching criteria.

**Comment by andrewsparkes** [comment]
UPDATE mlwhd_mlwarehouse_devdata.lighthouse_sample
INNER JOIN mlwhd_mlwarehouse_devdata.stock_resource
  ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode 
  AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
INNER JOIN mlwhd_mlwarehouse_devdata.sample 
  ON sample.id_sample_tmp = stock_resource.id_sample_tmp
  AND lighthouse_sample.root_sample_id = sample.description
  AND lighthouse_sample.result = sample.phenotype
SET lighthouse_sample.cog_uk_id = sample.supplier_name
WHERE lighthouse_sample.result = 'Positive'
AND lighthouse_sample.cog_uk_id IS NULL
AND lighthouse_sample.id > 0
;

CREATE INDEX index_lighthouse_sample_on_plate_barcode_and_coordinate
ON mlwhd_mlwarehouse_devdata.lighthouse_sample (plate_barcode, coordinate);

DROP INDEX index_lighthouse_sample_on_plate_barcode_and_coordinate ON mlwhd_mlwarehouse_devdata;

CREATE INDEX index_sample_on_phenotype
ON mlwhd_mlwarehouse_devdata.sample (phenotype);

DROP INDEX index_sample_on_phenotype ON mlwhd_mlwarehouse_devdata.sample;

CREATE INDEX index_stock_resource_on_plate_barcode_and_coordinate
ON mlwhd_mlwarehouse_devdata.stock_resource (labware_human_barcode, labware_coordinate);

DROP INDEX index_stock_resource_on_plate_barcode_and_coordinate ON mlwhd_mlwarehouse_devdata.stock_resource;

**Comment by andrewsparkes** [comment]
Possible process:

1. Create indexes
2. Run update
3. Drop indexes

Possible issue: Do we have permissions on MLWH RW user to create/drop indexes?

**Comment by andrewsparkes** [comment]
Also: sample.description is text and you cannot make an index on text fields due to their possible size.

**Comment by KatyTaylor** [comment]
This is what we actually ran on prod (~10.30 today)

```
-- Create the table indexes
CREATE INDEX index_lighthouse_sample_on_plate_barcode_and_coordinate
ON mlwarehouse.lighthouse_sample (plate_barcode, coordinate);

CREATE INDEX index_sample_on_phenotype
ON mlwarehouse.sample (phenotype);

CREATE INDEX index_stock_resource_on_plate_barcode_and_coordinate
ON mlwarehouse.stock_resource (labware_human_barcode, labware_coordinate);

-- Run the update
UPDATE mlwarehouse.lighthouse_sample
INNER JOIN mlwarehouse.stock_resource
  ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
  AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
INNER JOIN mlwarehouse.sample
  ON sample.id_sample_tmp = stock_resource.id_sample_tmp
  AND lighthouse_sample.root_sample_id = sample.description
  AND lighthouse_sample.result = sample.phenotype
SET lighthouse_sample.cog_uk_id = sample.supplier_name
WHERE lighthouse_sample.result = 'Positive'
AND lighthouse_sample.cog_uk_id IS NULL
AND lighthouse_sample.id > 0
;

-- Drop the table indexes
DROP INDEX index_lighthouse_sample_on_plate_barcode_and_coordinate ON mlwarehouse.lighthouse_sample;
DROP INDEX index_sample_on_phenotype ON mlwarehouse.sample;
DROP INDEX index_stock_resource_on_plate_barcode_and_coordinate ON mlwarehouse.stock_resource;
```
