### ISSUE TITLE
iseq_flowcell table: add external release column

### ISSUE THREAD

**Issue by mgcam** [sanger/unified_warehouse#15]
Requested by Rob D.  Type - boolean (or short int). This flag is used to decide whether the data have to be released. Default value - 1. Whenever manual qc value is changed, this flag has to be updated to reflect the change. Customers can request to overwrite the flag, ie, typically, change 0 to 1.

**Comment by JamesGlover** [comment]
Covered by iseq_flowcell.external_release. Defaults to NULL rather than 1, agreed upon in discussion.
