### ISSUE TITLE
GPL-769 Add a view for cherry-picked samples to make querying from lighthouse and crawler easier

### ISSUE THREAD

**Issue by pjvv** [sanger/unified_warehouse#152]
**User story**
As a developer I would like a view to the cherry-picked samples which joins the MLWH and events to get a unified view on which samples have been cherry-picked. This will allow us to optimise the query from crawler and lighthouse.

**Who are the primary contacts for this story**
Philip

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] add a view to the unified_warehouse (or somewhere common)
- [x] update crawler to use this view
- [x] update lighthouse to use this view
- [x] Remove the generation of structure.sql on each migration and rollback to use schema.rb
- [x] Move views creations from views_warehouse into unified_warehouse
- [x] Add views_schema gem to unified_warehouse
- [x] Generate Dockerfile for events warehouse project so we can use it to generate a new events_warehouse database when testing unified_warehouse new views
- [x] Create test to check the new views

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by pjvv** [comment]
> Might actually be call for a new repo to contain the creation SQL for views

**Comment by Chris-Friend** [comment]
Deployment branch for these changes is https://github.com/sanger/deployment/tree/GPL-769-cherrypicked-samples-view

**Comment by emrojo** [comment]
Project with the views: https://github.com/emrojo/views_warehouse

**Comment by emrojo** [comment]
Gem library for views_schema: https://github.com/emrojo/views_schema

**Comment by emrojo** [comment]
- [ ] Remove the generation of structure.sql on each migration and rollback to use schema.rb
- [ ] Move views creations from views_warehouse into unified_warehouse
- [ ] Add views_schema gem to unified_warehouse
- [ ] Generate Dockerfile for events warehouse project so we can use it to generate a new events_warehouse database when testing unified_wraehouse new views
- [ ] Create test to check the new views

**Comment by emrojo** [comment]
This is a summary of all related changes for this story to work, as it is in a lot of different projects:

Depending projects/pull requests:

* Dockerization of EWH: https://github.com/sanger/event_warehouse/pull/135
* Main changes for creating the view: https://github.com/sanger/unified_warehouse/pull/167
* Changes to use the view in Crawler: https://github.com/sanger/crawler/pull/249
* Changes to use the view in Lighthouse: https://github.com/sanger/lighthouse/pull/250

And a new project to move into Sanger:

https://github.com/emrojo/views_schema
