### ISSUE TITLE
BUG - Message loss when database is unavailable

### ISSUE THREAD

**Issue by JamesGlover** [sanger/unified_warehouse#159]
**Describe the bug**
On Wednesday 16th December the DBA's killed active database connections in an attempt to resolve a deadlock. This unsurprisingly resulted in issues with the ml warehouse, which started seeing exceptions along the lines of:

Mysql2::Error: MySQL client is not connected

In this situation the warehouse is supposed to sleep and wait until the database connection is restored. Any messages being processed when this exception occurs should be nacked, and thus returned to the queue for re-processing when the connection recovered.

However, several messages that were being processed during this time appear to have been lost. It is likely that we were accidentally acking them.

It is probably worth considering approaching this story alongside:
https://github.com/sanger/event_warehouse/issues/77

Essentially this would unify consumer creation in the warren gem:
https://github.com/sanger/warren

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by stevieing** [comment]
Closed as being addressed in other stories
