### ISSUE TITLE
GPL-844 MLWH Lighthouse sample table 'must be sequenced' & 'sequenced preferentially'

### ISSUE THREAD

**Issue by rl15** [sanger/unified_warehouse#172]
**User story**
GPL-844 As core LIMS team we woudl like to broadcast to Lighthouse_sample table if sample is of importance for reporting to PAM

**Who are the primary contacts for this story**
Callum S (PAM)
Ryes (PAM)
Sonia G (PAM)
Cristina A (PAM)
Harry C
Philip VV
Eduardo MR

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Update Lighthouse sample table two new fields
- [x] 'must be sequenced
- [x] 'sequenced preferentially'

Persist into DART for Beckman 'pickable' (covered in another story)
- To get the sample into DART as 'pickable' (regardless of whether they pass result / CT business rules), we either need to modify the code that chooses which samples to insert to DART, or modify the code that chooses whether to set 'filtered_positive' to true (probably the first option?)

**Dependencies**

**Additional context**
See parent backlog item GPL-801 As a Sanger scientist at a LH Lab I want to scan a LH plate and know if it contains a sample from Business or holiday traveler returning to UK (Importation) #103

**Comment by rl15** [comment]
From meeting on 4th Feb General approach of 'must be sequenced' & 'sequenced preferentially' has been discussed between Callum S & Sonia G and confirmed as good strategy.

**Comment by harrietc52** [comment]
On deploy: run migrations
