### ISSUE TITLE
GPL-896 Add index for filtered_positive column on MLWH lighthouse_sample table

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/unified_warehouse#189]
**User story**
To speed up querying for filtered positives we would like to add an index to the MLWH lighthouse_sample table.

**Who are the primary contacts for this story**
Devs, PAM

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] use of index when selecting filtered positives rather than table scanning

**Dependencies**
None

**Additional context**
Reporting from lighthouse samples table slow (see RT 712795)

**Comment by stevieing** [comment]
Add an index on cog uk id.

**Comment by rl15** [comment]
Aim to roll out to production 8th March 12pm.
