### ISSUE TITLE
GPL-911 - improve design / performance of lighthouse_sample table now approaching 30M rows

### ISSUE THREAD

**Issue by rl15** [sanger/unified_warehouse#191]
**User story**
As representative for DSA (David H) I would like to suggest a number of improvements to lighthouse_sample table to improve its performance 

**Who are the primary contacts for this story**
David H (DSA)
Ian W (PAM)
Tom W 

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] change source and result from varchar(255) to the ENUM data type (or as integer ID references to auxiliary dictionary tables containing the string values.)
- [ ] Change mongo_id so ... TBD
- [ ] move the plate ID to a separate dictionary table (called lighthouse_plate) and replace the column in lighthouse_sample with an integer ID reference to that dictionary.  I would also replace the index on rna_id with a composite index on the new plate ID number and the coordinate
- [ ] Notify PAM & Lee W if making this change (Impacts on Cotrack)

**Additional context**
David H wrote (Monday, 1 March 2021 at 07:19)

 Before I joined the DBA team, I developed a large-scale sequence tracking system based on a MySQL database, so I have some insight into what works well in MySQL and what doesn’t.  I hope you’ll allow me to offer a few observations as one developer to another.

Some of the columns, such as ‘source’ and ‘result’, are varchar(255) with a very small number of distinct values.  These would be better as either enumerations (the ENUM data type) or as integer ID references to auxiliary disctionary tables containing the string values.

The mongo_id column has a very small number of prefix strings: in a table of 25 million rows, there are only 1405 distinct values for the first 18 characters in this column.  The values are all 24 characters long.  I got the figure of 1405 by running this query:

select count(distinct(mongo_pfx)) from
(
select substring(mongodb_id,1,18) as mongo_pfx from lighthouse_sample
) Q

and changing the sampled prefix length of 18 to 20 still gives only 1849 distinct values.  This makes it a very poor candidate for indexing.

The rna_id column appears to be a concatenation of the plate ID and the coordinate within the plate (with a leading zero added), yet both of those strings are stored in separate columns, leading to redundancy and another example of sub-optimal indexing.  If I were designing this table, I would move the plate ID to a separate dictionary table (called lighthouse_plate) and replace the column in lighthouse_sample with an integer ID reference to that dictionary.  I would also replace the index on rna_id with a composite index on the new plate ID number and the coordinate.

I appreciate that much of your code is designed to work with the table as it currently exists, so changing the schema is going to involve re-working the code, especially for adding new data.  But this table is only going to continue growing, and the performance problems will worsen.  There’s only so much that we, the DBA team, can do to mitigate this by tweaking database-wide settings.  At some point, the inherent weaknesses of the table design will need to be addressed.  I’m happy to work with you and Simon to find solutions.

**Comment by TWJW-SANGER** [comment]
Deprecated by Product Owner.
Also noted that changing the table structure would impact queries and updates used in multiple applications.
