### ISSUE TITLE
GPL-859-3 - back populate uuids for sentinel samples

### ISSUE THREAD

**Issue by stevieing** [sanger/unified_warehouse#204]
**User story**
Back populate UUIDs for samples which originated from the Sentinel process

**Who are the primary contacts for this story**
Steve
Philip

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] create a SQL script to update the UUIDs in `lighthouse_sample` table to match those in `sample`
- ~update the sample UUIDs in mongo to match those in `lighthouse_sample`~
- ~update the samples in DART (well properties) with the updated sample UUID~

**Dependencies**
This story is blocked by the following dependencies:
- sanger/lighthouse#285

**References**
This story has a non-blocking relationship with:
- #184 

**Additional context**

**Comment by stevieing** [comment]
#184

**Comment by pjvv** [comment]
## MySQL Query

I have found 2M rows takes ~50s.

```sql
UPDATE lighthouse_sample
        INNER JOIN
    stock_resource ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
        AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
        INNER JOIN
    sample ON sample.id_sample_tmp = stock_resource.id_sample_tmp
        AND lighthouse_sample.root_sample_id = sample.description
        AND lighthouse_sample.result = sample.phenotype 
SET 
    lighthouse_sample.lh_sample_uuid = sample.uuid_sample_lims
WHERE
    lighthouse_sample.id >= x
        AND lighthouse_sample.id < y
```

**Comment by pjvv** [comment]
Updated script to achieve the same:
```sql
UPDATE lighthouse_sample
        INNER JOIN
    stock_resource ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
        AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
        INNER JOIN
    sample ON sample.id_sample_tmp = stock_resource.id_sample_tmp
        AND lighthouse_sample.root_sample_id = sample.description
        AND lighthouse_sample.result = sample.phenotype 
SET 
    lighthouse_sample.lh_sample_uuid = sample.uuid_sample_lims
WHERE
    lighthouse_sample.id >= 0
        AND lighthouse_sample.lh_sample_uuid <> sample.uuid_sample_lims;
```

Performed on `mlwhd_mlwarehouse_devdata`: `562 row(s) affected Rows matched: 562  Changed: 562  Warnings: 0
`

**Comment by stevieing** [comment]
> Updated script to achieve the same:
> 
> ```sql
> UPDATE lighthouse_sample
>         INNER JOIN
>     stock_resource ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
>         AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
>         INNER JOIN
>     sample ON sample.id_sample_tmp = stock_resource.id_sample_tmp
>         AND lighthouse_sample.root_sample_id = sample.description
>         AND lighthouse_sample.result = sample.phenotype 
> SET 
>     lighthouse_sample.lh_sample_uuid = sample.uuid_sample_lims,
>     lighthouse_sample.updated_at = NOW()
> WHERE
>     lighthouse_sample.id >= 0
>         AND lighthouse_sample.lh_sample_uuid <> sample.uuid_sample_lims;
> ```

All seems fine but not sure of the significance of it?
