### ISSUE TITLE
GPL-859-5 - modify uuid fields for sample and lighthouse_sample to be binary

### ISSUE THREAD

**Issue by stevieing** [sanger/unified_warehouse#205]
**User story**
modify uuid fields for sample and lighthouse_sample to be binary. Initial investigation showed that there was a 30% performance increase. Further investigation needs to be done to check to ensure that this will not have any side effects.

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by TWJW-SANGER** [comment]
Deprecated by the Product Owner.

**Comment by TWJW-SANGER** [comment]
Carl R does not think this is still a problem.
Deprecated by the Product Owner.
