### ISSUE TITLE
GPL-952 Do we have flow cell id and XP in MLWH NPG tables to deliver billing request from Rich R?

### ISSUE THREAD

**Issue by rl15** [sanger/unified_warehouse#213]
**Description**
A brief description of the research to be carried out.

**Who the primary contacts are for this work**
e.g. John Smith

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by JamesGlover** [comment]
Related: https://github.com/sanger/sequencescape/issues/2565

**Comment by JamesGlover** [comment]
XP or not appears to be in the workflow_type column of iseq_run_lane_metrics

**Comment by JamesGlover** [comment]
flowcell_barcode is also in the iseq_run_lane_metrics table

**Comment by JamesGlover** [comment]
Finding out about flowcell type:

> Hello Both,
>  
> We have a request from Rich R to update the billing reports to include flowcell type (SP, S4 & S2) and workflow type (XP/non XP) for novaseq lanes.
>  
> We moved the tracking of this information out of Sequencescape as it was prone to user error, and my understanding is you are now extracting the information from the sequencing machines themselves.
>  
> As far as I can tell:
>  
> The workflow is presented in the workflow_type column of iseq_run_lane_metrics
>  
> But I can’t find the flowcell type, although seem to recall that this can be derived from the flowcell barcode.
>  
> Do you have any information about where we can extract flowcell type, or how we might be able to derive it.
>  
> Thank you,
>  
> James

**Comment by JamesGlover** [comment]
Resonse from Marina:
> > 
> > We have a request from Rich R to update the billing reports to include flowcell type (SP, S4 & S2) and workflow type (XP/non XP) for novaseq lanes.
>
> SP, etc. is called Flowcell Mode and is reported in the RunParameters.xml file located in the Illumina run folder
>  
> > The workflow is presented in the workflow_type column of iseq_run_lane_metrics
>
> Yes
>  
> > But I can’t find the flowcell type,
>
> We were never asked to provide this information
>
> > although seem to recall that this can be derived from the flowcell barcode.
>
> I cannot see how it can be done, but I am not the highest authority on this
>  
> > Do you have any information about where we can extract flowcell type, or how we might be able to derive it.
>
> Advise Rich R. to ask NPG to provide this information in iseq_run_lane_metrics?
> 
...

**Comment by JamesGlover** [comment]
Sent this information on to Rich R and Rich L

**Comment by JamesGlover** [comment]
Not quite sure what is meant by flowcell id in this story title.

**Comment by KatyTaylor** [comment]
Removing from project as we might not have to do this work

**Comment by JamesGlover** [comment]
This information is now present and populated by NPG.
