### ISSUE TITLE
GPL-980-02 BUG - Sentinel MLWH cog_uk_id not updated on plate creation (safe)

### ISSUE THREAD

**Issue by emrojo** [sanger/unified_warehouse#220]
**Describe the bug**

As described [here](https://github.com/sanger/lighthouse/issues/318), the table `lighthouse_sample` does not have the `cog_uk_id` field populated as it is in the `samples` table. 

Fixing this problem requires running two queries (safe and unsafe). We have broken this is into two stories, GPL-980-02 (this one), which contains the **safe** query, and [GPL-980-03](https://github.com/sanger/unified_warehouse/issues/234) which contains the **unsafe** query. 

The below query is **safe** becuse it only updates the cog uk id if it is null.

As both implies a change in the warehouse, it requires to notify the users about this change before applying it.

**Acceptance criteria**

- [ ] All lighthouse samples where the cog uk id was null, should now be matching the samples supplier name

**Additional context**
[Similar](https://ssg-confluence.internal.sanger.ac.uk/display/PSD/How+to+migrate+Cog+UK+IDs+into+the+lighthouse_sample+table) migration has already been done before so can re-use.

Scenario 2 from [GPL-853](https://github.com/sanger/General-Backlog-Items/issues/113) may also be getting covered here, as "COG UK IDs propagated to lighthouse_sample (as per all Lighthouse samples)" 

Nonmatching UUIDs:
Also found during this story is that 84 (as of 05.05.21) lighthouse samples have the incorrect uuid (they dont match the sample's uuid) see [story](https://github.com/sanger/unified_warehouse/issues/231 )

**Comment by rl15** [comment]
Expected Ben to pick up.

**Comment by harrietc52** [comment]
Steps to backfilling cog uk id where missing on positive samples
- [ ] Update Katy's rake task 
- [ ] get local copy of data
- [ ] test on uat
- [ ] test on training
- [ ] email warehouse users 
- [ ] run on prod

**Comment by harrietc52** [comment]
Scenario 2 from [GPL-853](https://github.com/sanger/General-Backlog-Items/issues/113) may also be getting covered here, as "COG UK IDs propagated to lighthouse_sample (as per all Lighthouse samples)"

**Comment by harrietc52** [comment]
Confluence page with original SQL lighthouse sample table update  [here](https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?spaceKey=PSD&title=How+to+migrate+Cog+UK+IDs+into+the+lighthouse_sample+table)

**Comment by harrietc52** [comment]
SQL

```
-- Run the update
UPDATE mlwarehouse.lighthouse_sample
INNER JOIN mlwarehouse.sample
  ON sample.uuid_sample_lims = lighthouse_sample.lh_sample_uuid
SET lighthouse_sample.cog_uk_id = sample.supplier_name
WHERE lighthouse_sample.cog_uk_id IS NULL
AND sample.supplier_name IS NOT NULL
-- AND lighthouse_sample.id > 0
;
```

**Comment by harrietc52** [comment]
Query to check how many lighthouse samples exist with a cog uk id, but that the cog uk id doesnt match the supplier name in the samples table

```sql
SELECT * FROM unified_warehouse_development.sample
INNER JOIN lighthouse_sample ON lighthouse_sample.lh_sample_uuid=sample.uuid_sample_lims
WHERE lighthouse_sample.cog_uk_id IS NOT NULL AND sample.supplier_name IS NOT NULL -- includes empty strings
AND lighthouse_sample.cog_uk_id <> sample.supplier_name;
```

**Comment by harrietc52** [comment]
Query to get all samples, that have a linked lighthouse sample, where the samples supplier name is an empty string and lighthouse cog uk id is null

```sql
SELECT * FROM unified_warehouse_development.sample
INNER JOIN lighthouse_sample ON lighthouse_sample.lh_sample_uuid=sample.uuid_sample_lims
WHERE NULLIF(sample.supplier_name, '') IS NULL
AND lighthouse_sample.cog_uk_id IS NULL
;
```

**Comment by emrojo** [comment]
There are 1352 samples where cog_uk_id is different between lighthouse_sample and sample. Initial look at the issue:

Possible causes:
* 1. Eagle samples are uploaded via manifest, which it could potentially overwrite cog_uk_ids
* 2. There has been some updates of cog_uk_ids in the samples in the past, in that case the old cog_uk_id was stored in the donor_id
* 3. Samples have been linked in the past with lighthouse_sample by using root_sample_id, the link could have been incorrect in some cases 

Looking at these options:
* 1. Samples with the problem do not have a manifest associated
* 2. Samples with the problem do not have any value in the donor_id so we don't think in this group of samples
* 3. Checking this one for the moment

**Comment by harrietc52** [comment]
Cause 2:
Joining on uuid, there are no samples where lighthouse_sample.cog_uk_id = sample.donor_id

**Comment by harrietc52** [comment]
TODO

Test using old join, prior to uuid. Example sql from [here](https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?spaceKey=PSD&title=How+to+migrate+Cog+UK+IDs+into+the+lighthouse_sample+table)
Below requires indexes too
```sql
SELECT COUNT(id) FROM mlwhd_mlwarehouse_proddata.lighthouse_sample
INNER JOIN mlwhd_mlwarehouse_proddata.stock_resource
  ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
  AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
INNER JOIN mlwhd_mlwarehouse_proddata.sample
  ON sample.id_sample_tmp = stock_resource.id_sample_tmp
  AND lighthouse_sample.root_sample_id = sample.description
  AND lighthouse_sample.result = sample.phenotype
WHERE sample.supplier_name IS NOT NULL
AND lighthouse_sample.cog_uk_id IS NOT NULL
AND lighthouse_sample.cog_uk_id <> sample.supplier_name
;
```

**Comment by harrietc52** [comment]
scrap
we know there are uuid
dont use uuid to join
use old query


check where donor id set, if created at and updated at are equal, 
might show that it has been updated, manually


```
mib114551i:python_script_test hc6$ python diff_cog_uk_id.py
['\xef\xbb\xbfroot_sample_id']
['\xef\xbb\xbfroot_sample_id']
['root_sample_id']
Length of uuid join set 1352.
Length of old join set 1411.
Length of union 1411.
Length of diff 59.
Samples in diff:
set(['AAH02719922', 'AAD04198088', 'AAH02719656', 'AAH18208472', 'AAE04389591', 'AAH02719830', 'AAE04389881', 'AAF95588377', 'AAF31475877', 'AAF31475143', 'AAD55627575', 'AAF31476904', 'AAH02719694', 'AAF31475075', 'AAF31459624', 'AAD20636625', 'AAD04198507', 'AAE04389645', 'AAF31476881', 'AAH18201442', 'AAH02719939', 'AAD55627636', 'AAD55626929', 'AAH02719854', 'AAE04389973', 'AAH02727118', 'AAF31459686', 'AAE04389652', 'AAF31477628', 'AAC12309217', 'AAF31476942', 'AAE04389959', 'AAF31476867', 'AAD04197302', 'AAE04387856', 'AAF31459730', 'AAD04195360', 'AAF31475129', 'AAH10706792', 'AAF95588599', 'AAF95588391', 'AAF31476768', 'AAF31476911', 'AAF31459617', 'AAH02719892', 'AAF95588346', 'AAC12309125', 'AAE04389713', 'AAF31476874', 'AAD04197807', 'AAE04389751', 'AAF95639246', 'AAH02727101', 'AAE04389621', 'AAF95639260', 'AAE04389843', 'AAF95587219', 'AAD04198576', 'AAF31476829'])
Length of mistmatch uuid set 84.
Length of union_of_missmatch_and_diff 84.
Length of mistmatch/uuid diff set 25.
Samples in diff_of_missmatch:
set(['AAI47316963', 'AAD20511496', 'AAI47317502', 'AAD20513254', 'AAI47316789', 'AAI46187977', 'AAH22229388', 'AAG72020585', 'AAH22229487', 'AAD20513223', 'AAI48722763', 'AAH18201466', 'AAD20513100', 'AAG72020608', 'AAG72021766', 'AAD20513261', 'AAI48765371', 'AAI44936904', 'AAI48722954', 'AAI48775615', 'AAI46186468', 'AAD20513117', 'AAD20511816', 'AAI48775349', 'AAH22229371'])
```

**Comment by harrietc52** [comment]
Sample table => source of truth
mongo / sample / lighthouse sampe

**Comment by harrietc52** [comment]
Cause of 1411 samples 


84 samples uuid dont match

**Comment by harrietc52** [comment]
Number of samples where cogukid is null and supplier name is not null, and they are different

```sql
SELECT * FROM mlwhd_mlwarehouse_proddata.lighthouse_sample
INNER JOIN mlwhd_mlwarehouse_proddata.stock_resource
  ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
  AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
INNER JOIN mlwhd_mlwarehouse_proddata.sample
  ON sample.id_sample_tmp = stock_resource.id_sample_tmp
  AND lighthouse_sample.root_sample_id = sample.description
  AND lighthouse_sample.result = sample.phenotype
WHERE lighthouse_sample.cog_uk_id IS NULL
AND sample.supplier_name IS NOT NULL
AND lighthouse_sample.cog_uk_id <> sample.supplier_name
;
```

**Comment by harrietc52** [comment]
SELECT * FROM mlwhd_mlwarehouse_proddata.lighthouse_sample INNER JOIN mlwhd_mlwarehouse_proddata.stock_resource   ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode   AND stock_resource.labware_coordinate = lighthouse_sample.coordinate INNER JOIN mlwhd_mlwarehouse_proddata.sample   ON sample.id_sample_tmp = stock_resource.id_sample_tmp   AND lighthouse_sample.root_sample_id = sample.description   AND lighthouse_sample.result = sample.phenotype WHERE lighthouse_sample.cog_uk_id IS NULL AND sample.supplier_name IS NOT NULL AND lighthouse_sample.cog_uk_id <> sample.supplier_name LIMIT 0, 1500

**Comment by harrietc52** [comment]
Originally linked to [PR](https://github.com/sanger/unified_warehouse/pull/224), but closed as no changes required

**Comment by harrietc52** [comment]
Part 1. From Dec
Samples dont match

Part 2. From 11th March 

Update to `plates.py`, merged to master 

From develop into master [PR](https://github.com/sanger/lighthouse/pull/269) in plates.py
`if response.ok:` -> changed to `if response.status_code == HTTPStatus.OK:`

From [here](https://www.w3schools.com/python/ref_requests_response.asp) `response.ok` returns true where response code is less that 400, which would include both HTTPStatus.OK and HTTPStatus.CREATED. So the change to HTTPStatus.OK, stopped populating the cog uk ids

**Comment by harrietc52** [comment]
All samples:
doesnt say it has a manifest
is a source plate
must have come through sentinal
bug in sentinal

1495 -- inner query, getting duplicates
1411 - mismatch

Sentinel import all samples on plate, some have then been process by Beckman so duplicate root sample id
=> 84 ish samples have duplicates Root Sample ID, at 12:10  on 31st December
one plate of duplicates
Two plates got created at the same time: 
http://training.sequencescape.psd.sanger.ac.uk/labware/27150529 
http://training.sequencescape.psd.sanger.ac.uk/labware/27150526
could be race condition bug (double clicking really fast!?)

**Comment by rl15** [comment]
rem to notify mlwh-notices@sanger.ac.uk
