### ISSUE TITLE
GPL-997 As developer for DT4 in PAM (Rhys) I would like to add updated_at indexes to relevant MLWH tables so that Heron reporting is faster and more robust.

### ISSUE THREAD

**Issue by rl15** [sanger/unified_warehouse#229]
**User story**
GPL-997 | As developer for DT4 in PAM (Rhys) I would like to add updated_at indexes to relevant MLWH tables so that Heron reporting is faster and more robust.

**Who are the primary contacts for this story**
Rhys M
David H (unintended consequences?)

**Acceptance criteria**
To be considered successful the solution must allow:

 - [ ] Further discussion on 6th May to have 
 - [ ] ALTER TABLE `all_relevant_tables` ADD COLUMN `last_updated` `DateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ;
- [ ] ALTER TABLE `all_relevant_tables` ADD INDEX `index_last_updated` (`last_updated`);
- [ ] Test on UAT before production

Note: These changes should be performed via Rails migrations, preferably using the 'Rails Way' in order to ensure consistency across environments. See:
- https://guides.rubyonrails.org/active_record_migrations.html
- https://api.rubyonrails.org/v6.0.4/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_index

**Additional context**
From DT2/DT6 meeting on 5th May

**Comment by rl15** [comment]
Rhys M wrote (Wednesday, 5 May 2021 at 14:22)

To expand on my reasoning. If we had this in all tables, there is a potential to efficiently mirror MLWH in a datastore more suited for the sort of resource intensive queries that DT-6 needs to run. This is still in the feasibility analysis stage, but we could efficiently update a single sharded datastore in real time from MLWH and have all analytics queries run on that instead through a distributed processing framework. This would solve DT-4’s ETL timescale problems as well as relieve you of query performance questions (on the analytics end).

**Comment by JamesGlover** [comment]
last_update is usually populated based on the timestamp in the message coming from the parent lims (such as Sequencescape) and is used to determine whether incoming records are more recent than the existing recorded version. If we populated it based on the time it hit the warehouse, then any inflight updates would get lost. recorded_at is the column that indicates when the message hit the warehouse.

(Although I'm not sure what the 'all_relevant_tables' are, as most our tables have the column in already)

**Comment by JamesGlover** [comment]
If the main desire for the timestamp is to monitor WH changes, then recorded_at is actually the better stamp to check, as:
1) Under heavy load there can be significant delay between an entry being updated in the lims, and entry into the WH.
2) Messages from the Lims may not hit the WH in order.

**Comment by RMansel** [comment]
Hi James, recorded_at is absolutely fine if that is the preferable/more appropriate field. I just need an indexed timestamp on the relevant tables so I can efficiently and frequently select all new/changed rows .

**Comment by RMansel** [comment]
I read further up and saw the request to clarify 'relevant tables'. This would be any table that analytics queries might be run on. If I could have every table, that would reduce the number of caveats I need to make to users. In case this is not feasible for some reason, I'll get a list of tables in use for existing and planned processes early next week.

**Comment by JamesGlover** [comment]
The following tables are managed by the warehouse builders, and already have a recorded_at column. These should be easy to update:

- bmap_flowcell
- flgen_plate
- iseq_flowcell
- oseq_flowcell
- pac_bio_run
- qc_result
- sample
- samples_extraction_activity
- stock_resource
- study

This table is managed by the WH builders, but through a slightly different mechanism. It doesn't currently have
a recorded_at timestamp. The current mechanism of updating means that *all* users are destroyed and recreated
whenever the study is updated. Given that changes to this table include deletions, monitoring a recorded at timestamp wouldn't be sufficent to detect all changes.
- study_users

This table is maintained by us, outside the usual warehouse building mechanisms. It would need changes elsewhere to populate a recorded at column. (Although created_at may be sufficient?)
- lighthouse_sample

All other tables are maintained by NPG.

**Comment by RMansel** [comment]
I just realised this might work better if we instead produced separate tables for changes and populated them via mysql trigger functions on insert, update and delete actions (at the cost of significant additional data storage and some reduction in performance on change related actions)

**Comment by JamesGlover** [comment]
We used to do that for the legacy warehouse. Then we had our permission to create triggers taken away.

**Comment by RMansel** [comment]
I think we may need to talk to the DBAs then. It is not possible to implement CDC on tables which can have deletions without the use of triggers or access to the binary log.

**Comment by KatyTaylor** [comment]
Google Doc with explanation of problem and discussion of options: https://docs.google.com/document/d/1_dLmVRPsLnGSrgUaMwzxnLWASvkpDqKJhOaoruNgrQ8/edit?usp=sharing

Meeting today to discuss options.

**Comment by KatyTaylor** [comment]
Meeting with PaM (Rhys), DBAs (David & Simon), PSD (me & James), NPG (David & Marina) today:

Decided on DBA-owned Debezium / PaM-owned Kafka as the solution. DBAs have already done some testing of Debezium. We and NPG might have to produce some test data / inserts / updates / deletes to assist with testing in the future, but for now I will mark this as done as it doesn't require input from PSD.
