### ISSUE TITLE
GPL-980-03 BUG - Sentinel MLWH cog_uk_id not updated on plate creation (unsafe)

### ISSUE THREAD

**Issue by harrietc52** [sanger/unified_warehouse#234]
**Describe the bug**

As described [here](https://github.com/sanger/lighthouse/issues/318), the table `lighthouse_sample` does not have the `cog_uk_id` field populated as it is in the `samples` table. 

Fixing this problem requires running two queries (safe and unsafe). We have broken this is into two stories, GPL-980-03 (this one) which contains the **unsafe** query, and [GPL-980-02](https://github.com/sanger/unified_warehouse/issues/220) , which contains the **safe** query. 

The below query is **unsafe** because it updates the cog uk id where it isn't null, therefore it would overwrite ~1000 lighthouse samples where the cog uk id is already populated

As both implies a change in the warehouse, it requires to notify the users about this change before applying it.

**Acceptance criteria**

- [ ] All lighthouse samples where the cog uk id is not null, should now be matching the samples supplier name (**check this is correct**)

**Additional context**
[Similar](https://ssg-confluence.internal.sanger.ac.uk/display/PSD/How+to+migrate+Cog+UK+IDs+into+the+lighthouse_sample+table) migration has already been done before so can re-use.

Scenario 2 from [GPL-853](https://github.com/sanger/General-Backlog-Items/issues/113) may also be getting covered here, as "COG UK IDs propagated to lighthouse_sample (as per all Lighthouse samples)" 

Nonmatching UUIDs:
Also found during this story is that 84 (as of 05.05.21) lighthouse samples have the incorrect uuid (they dont match the sample's uuid) see [story](https://github.com/sanger/unified_warehouse/issues/231 )

**Comment by harrietc52** [comment]
SQL 2 - **THIS IS NOT SAFE - NEED TO CHECK**
```sql
SELECT * FROM lighthouse_sample
INNER JOIN stock_resource
  ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
  AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
INNER JOIN sample
  ON sample.id_sample_tmp = stock_resource.id_sample_tmp
  AND lighthouse_sample.root_sample_id = sample.description
  AND lighthouse_sample.result = sample.phenotype
WHERE sample.supplier_name IS NOT NULL
AND lighthouse_sample.cog_uk_id IS NOT NULL
AND lighthouse_sample.cog_uk_id <> sample.supplier_name
AND lighthouse_sample.result = 'Positive'
;
-- 1411 (05.05.21)
```

**Comment by harrietc52** [comment]
Need to check below, as SQL 2 would currently overwrite 1411 lighthouse sample cogukid's. Question: Does the currently lighthouse sample cog uk id, want to be updated to match the samples supplier name, or should they be left different?

**Comment by harrietc52** [comment]
**THIS NEED CONFIRMING, AS IT INVOLVES OVERWRITING THE CURRENT COGUKID**
```sql
UPDATE lighthouse_sample
INNER JOIN stock_resource
  ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
  AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
INNER JOIN sample
  ON sample.id_sample_tmp = stock_resource.id_sample_tmp
  AND lighthouse_sample.root_sample_id = sample.description
  AND lighthouse_sample.result = sample.phenotype
SET 
  lighthouse_sample.cog_uk_id = sample.supplier_name,
  lighthouse_sample.updated_at = NOW()
WHERE sample.supplier_name IS NOT NULL
  AND lighthouse_sample.cog_uk_id IS NOT NULL
  AND lighthouse_sample.cog_uk_id <> sample.supplier_name
  AND lighthouse_sample.result = 'Positive'
;
```
-- 1411

**Comment by harrietc52** [comment]
Prep:
- [x] Create query
- [ ] Test on UAT
- [ ] Test on Training
- [ ] Give required notification - email warehouse users 
- [ ] Run on prod

Steps: 
- [ ] Check there are no supplier names or cog uk ids that are empty strings (SQL 3)
- [ ] Check number of lighthouse samples to be updated (Run SQL 1)
- [ ] Run query (SQL 2) update
- [ ] Check number of lighthouse samples - should be 0 (Run SQL 1)
- [ ] Check if Beckman/ Crawler running

**Comment by harrietc52** [comment]
Get the list of samples to update:

SQL 1
```sql
SELECT * FROM lighthouse_sample
INNER JOIN stock_resource
  ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
  AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
INNER JOIN sample
  ON sample.id_sample_tmp = stock_resource.id_sample_tmp
  AND lighthouse_sample.root_sample_id = sample.description
  AND lighthouse_sample.result = sample.phenotype
WHERE sample.supplier_name IS NOT NULL
AND lighthouse_sample.cog_uk_id IS NOT NULL
AND lighthouse_sample.cog_uk_id <> sample.supplier_name
AND lighthouse_sample.result = 'Positive'
;
-- 1411 (05.05.21)
```

Update those samples:

SQL 2

**THIS NEED CONFIRMING, AS IT INVOLVES OVERWRITING THE CURRENT COGUKID**
Need to check below, as SQL 2 would currently overwrite 1411 lighthouse sample cogukid's. Question for PAM: Does the currently lighthouse sample cog uk id, want to be updated to match the samples supplier name, or should they be left different?


```sql
UPDATE lighthouse_sample
INNER JOIN stock_resource
  ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
  AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
INNER JOIN sample
  ON sample.id_sample_tmp = stock_resource.id_sample_tmp
  AND lighthouse_sample.root_sample_id = sample.description
  AND lighthouse_sample.result = sample.phenotype
SET 
  lighthouse_sample.cog_uk_id = sample.supplier_name,
  lighthouse_sample.updated_at = NOW()
WHERE sample.supplier_name IS NOT NULL
  AND lighthouse_sample.cog_uk_id IS NOT NULL
  AND lighthouse_sample.cog_uk_id <> sample.supplier_name
  AND lighthouse_sample.result = 'Positive'
;
```
-- 1411

**Comment by harrietc52** [comment]
Query to get all samples, that have a linked lighthouse sample, where the samples supplier name is null or blank, or the lighthouse cog uk id is null or blank

SQL 3

SELECT COUNT(id_sample_tmp) FROM mlwarehouse.sample
INNER JOIN mlwarehouse.lighthouse_sample ON lighthouse_sample.lh_sample_uuid=sample.uuid_sample_lims
WHERE NULLIF(lighthouse_sample.cog_uk_id, '') IS NULL;

SELECT COUNT(id_sample_tmp) FROM mlwarehouse.sample
INNER JOIN mlwarehouse.lighthouse_sample ON lighthouse_sample.lh_sample_uuid=sample.uuid_sample_lims
WHERE NULLIF(sample.supplier_name, '') IS NULL;

prod_data: 0 samples

**Comment by harrietc52** [comment]
1. Uuid -
a. Using it to find mismatching cog uk id
b. Compare with old join gave mismatch of 85 samples (83 of which are duplicates based on old join)
c. Solution? Delete one of the duplicate plates
d. TODO: investigate final 2 samples

2. COG UK ID mismatching using old join -
a. Both supplier name and cog uk id are not null / empty, but don’t match (1,411 mismatch)
b. 83ish of these are from duplicate plates created by Sentinel at 12:10 31st Dec
c. A random one chosen from the others was created by Sentinel and then also by Beckman - lighthouse_sample id 22177103, root sample id / description AAA56966225 - has 2 rows in sample table
i. Could explain all the others, not confirmed
Spot check some samples - are there duplicates?
(Root sample id - SS sample ids)
AAC46426911 - 5241328, 5265635
AAD17325983 - 5505559, 5512265
AAB32222245 - 5538967, 5574506

**Comment by harrietc52** [comment]
Diagram of cog uk id mismatch https://lucid.app/lucidchart/8cfc3615-f1e3-4ef8-a0b3-739121fc3d5a/edit?page=0_0#

**Comment by harrietc52** [comment]
```sql
SELECT lighthouse_sample.id, lighthouse_sample.cog_uk_id, lighthouse_sample.root_sample_id,
      sample.id_sample_tmp, sample.supplier_name, sample.description
FROM lighthouse_sample
  
INNER JOIN sample
  ON lighthouse_sample.cog_uk_id = sample.supplier_name
  
WHERE lighthouse_sample.id IN 
-- dodgy samples
(
  SELECT lighthouse_sample.id
    FROM lighthouse_sample
    INNER JOIN stock_resource
      ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
      AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
      
    INNER JOIN sample
      ON sample.id_sample_tmp = stock_resource.id_sample_tmp
      AND lighthouse_sample.root_sample_id = sample.description
      AND lighthouse_sample.result = sample.phenotype
      
    WHERE sample.supplier_name IS NOT NULL
    AND lighthouse_sample.cog_uk_id IS NOT NULL
    AND lighthouse_sample.cog_uk_id <> sample.supplier_name
    AND lighthouse_sample.result = 'Positive'
) 
```

`lighthouse_sample.cog_uk_id = sample.supplier_name` joining on cog uk id gets matching beckman aswell as non matching sentinel

**Comment by neilsycamore** [comment]
There are 10 samples that have been uploaded to climb twice
[dup_climb_samples.csv](https://github.com/sanger/unified_warehouse/files/6466363/dup_climb_samples.csv)

**Comment by KatyTaylor** [comment]
This gives samples where both of the Sentinel / Beckman duplicates have been sequenced (are in iseq_flowcell table) - 133 samples - and shows whether or not sequence data has been uploaded to climb - 10 samples where it has for both duplicates

```
SELECT lighthouse_sample.id as lighthouse_sample_id, lighthouse_sample.root_sample_id, lighthouse_sample.plate_barcode, lighthouse_sample.coordinate as well,
      sample1.name as sample_1_name, sample1.supplier_name as cog_uk_id_1, sample1.created as sample_1_created, seq1.id_iseq_flowcell_tmp as sample_1_sequenced_id, hpm1.`climb_upload` as climb_1,
      sample2.name as sample_2_name, sample2.supplier_name as cog_uk_id_2, sample2.created as sample_2_created, seq2.id_iseq_flowcell_tmp as sample_2_sequenced_id, hpm2.`climb_upload` as climb_2
      
FROM lighthouse_sample
-- Sentinel samples - don't match on cog uk id, match on stock plate barcode + coord
INNER JOIN stock_resource
  ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
  AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
  
INNER JOIN sample as sample1
  ON sample1.id_sample_tmp = stock_resource.id_sample_tmp
  AND lighthouse_sample.root_sample_id = sample1.description
  AND lighthouse_sample.result = sample1.phenotype
  
-- Beckman samples - match on cog uk id
INNER JOIN sample as sample2
  ON lighthouse_sample.cog_uk_id = sample2.supplier_name
  
INNER JOIN iseq_flowcell as seq1
  ON sample1.id_sample_tmp = seq1.id_sample_tmp
LEFT JOIN iseq_product_metrics pm1
  ON pm1.id_iseq_flowcell_tmp = seq1.id_iseq_flowcell_tmp
LEFT JOIN iseq_heron_product_metrics hpm1
  ON hpm1.`id_iseq_product` = pm1.`id_iseq_product`
	

INNER JOIN iseq_flowcell as seq2
  ON sample2.id_sample_tmp = seq2.id_sample_tmp
LEFT JOIN iseq_product_metrics pm2
  ON pm2.id_iseq_flowcell_tmp = seq2.id_iseq_flowcell_tmp
LEFT JOIN iseq_heron_product_metrics hpm2
  ON hpm2.`id_iseq_product` = pm2.`id_iseq_product`


WHERE lighthouse_sample.id IN 
-- dodgy samples
(
  SELECT lighthouse_sample.id
    FROM lighthouse_sample
    INNER JOIN stock_resource
      ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
      AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
      
    INNER JOIN sample
      ON sample.id_sample_tmp = stock_resource.id_sample_tmp
      AND lighthouse_sample.root_sample_id = sample.description
      AND lighthouse_sample.result = sample.phenotype
      
    WHERE sample.supplier_name IS NOT NULL
    AND lighthouse_sample.cog_uk_id IS NOT NULL
    AND lighthouse_sample.cog_uk_id <> sample.supplier_name
    AND lighthouse_sample.result = 'Positive'
)
;
```

**Comment by KatyTaylor** [comment]
Variation on the above query from David J, which includes "qc (determines if suitable for sending to CLIMB), and a summary of the negative contol qc on the same lane (but that doesn't necessairily forbid sending if there's a fail).":

```
SELECT lighthouse_sample.id as lighthouse_sample_id, lighthouse_sample.root_sample_id, lighthouse_sample.plate_barcode, lighthouse_sample.coordinate as well,       
      sample1.name as sample_1_name, sample1.supplier_name as cog_uk_id_1, sample1.created as sample_1_created, seq1.id_iseq_flowcell_tmp as sample_1_sequenced_id, pm1.qc as qc_1, cpm1.qc as cqc_1, hpm1.`climb_upload` as climb_1,       
      sample2.name as sample_2_name, sample2.supplier_name as cog_uk_id_2, sample2.created as sample_2_created, seq2.id_iseq_flowcell_tmp as sample_2_sequenced_id, pm2.qc as qc_2, cpm2.qc as cqc_2, hpm2.`climb_upload` as climb_2        
FROM lighthouse_sample  
INNER JOIN stock_resource
   ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode   AND stock_resource.labware_coordinate = lighthouse_sample.coordinate    
INNER JOIN sample as sample1
   ON sample1.id_sample_tmp = stock_resource.id_sample_tmp   AND lighthouse_sample.root_sample_id = sample1.description   AND lighthouse_sample.result = sample1.phenotype     
INNER JOIN sample as sample2
   ON lighthouse_sample.cog_uk_id = sample2.supplier_name    
INNER JOIN iseq_flowcell as seq1
   ON sample1.id_sample_tmp = seq1.id_sample_tmp 
LEFT JOIN iseq_product_metrics pm1
   ON pm1.id_iseq_flowcell_tmp = seq1.id_iseq_flowcell_tmp 
LEFT JOIN iseq_heron_product_metrics hpm1
   ON hpm1.`id_iseq_product` = pm1.`id_iseq_product` 
JOIN 
(
  SELECT pm.id_run, pm.position, MIN(pm.qc) qc 
  FROM iseq_product_metrics pm 
  JOIN iseq_flowcell USING(id_iseq_flowcell_tmp) 
  JOIN sample USING(id_sample_tmp) 
  WHERE sample.control_type="negative" 
  GROUP BY pm.id_run, pm.position 
) cpm1
  ON pm1.id_run=cpm1.id_run AND pm1.position=cpm1.position  
INNER JOIN iseq_flowcell as seq2
   ON sample2.id_sample_tmp = seq2.id_sample_tmp 
LEFT JOIN iseq_product_metrics pm2
   ON pm2.id_iseq_flowcell_tmp = seq2.id_iseq_flowcell_tmp 
LEFT JOIN iseq_heron_product_metrics hpm2
 ON hpm2.`id_iseq_product` = pm2.`id_iseq_product` 
JOIN 
(
  SELECT pm.id_run, pm.position, MIN(pm.qc) qc 
  FROM iseq_product_metrics pm 
  JOIN iseq_flowcell USING(id_iseq_flowcell_tmp) 
  JOIN sample USING(id_sample_tmp) 
  WHERE sample.control_type="negative" 
  GROUP BY pm.id_run, pm.position 
) cpm2
  ON pm2.id_run=cpm2.id_run AND pm2.position=cpm2.position  
WHERE sample1.supplier_name <> sample2.supplier_name 
LIMIT 150;
```
Results show that the qc column matches up with climb_upload column - so all the rows here that were not sent to Climb were because of failed qc.

**Comment by KatyTaylor** [comment]
Confluence page - https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Duplicate+COG+UK+IDs+May+2021
