### ISSUE TITLE
DPL-026 [BUG] Missing uuids in lighthouse_sample [Heron]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/unified_warehouse#243]
**Describe the bug**
Some sample uuids are missing from the lighthouse_sample table. The RT describes it well (linked below).
Not sure what the root cause is, but presumably the [migration](https://github.com/sanger/unified_warehouse/issues/204) missed them for some reason.

**RT Ticket Number**
https://rt.sanger.ac.uk/Ticket/Display.html?id=720882

**Comment by sdjmchattie** [comment]
The original script to achieve the backport of UUIDs was as follows:

```
UPDATE lighthouse_sample
        INNER JOIN
    stock_resource ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
        AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
        INNER JOIN
    sample ON sample.id_sample_tmp = stock_resource.id_sample_tmp
        AND lighthouse_sample.root_sample_id = sample.description
        AND lighthouse_sample.result = sample.phenotype 
SET 
    lighthouse_sample.lh_sample_uuid = sample.uuid_sample_lims,
    lighthouse_sample.updated_at = NOW()
WHERE
    lighthouse_sample.id >= 0
        AND lighthouse_sample.lh_sample_uuid <> sample.uuid_sample_lims;
```

However this doesn't catch everything because `<>` cannot be used to compare a `NULL` value to a non-`NULL` value.  It will come back `false` if you compare, for example `NULL <> "An_ID"`.  So I propose the following script and will be trying this out on the production data clone.

```
UPDATE lighthouse_sample
INNER JOIN stock_resource
    ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
    AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
INNER JOIN sample
    ON sample.id_sample_tmp = stock_resource.id_sample_tmp
    AND lighthouse_sample.root_sample_id = sample.description
    AND lighthouse_sample.result = sample.phenotype
SET
    lighthouse_sample.lh_sample_uuid = sample.uuid_sample_lims,
    lighthouse_sample.updated_at = NOW()
WHERE
    lighthouse_sample.id >= 0
    AND lighthouse_sample.lh_sample_uuid IS NULL
    AND sample.uuid_sample_lims IS NOT NULL;
```

I have excluded the previous `<>` since those rows have already been updated.

**Comment by sdjmchattie** [comment]
I ran the above and it updated 500k+ rows.  I then tried the query that Ian Wright used to check on this issue:

```
SELECT count(*), MAX(date_tested)
FROM lighthouse_sample
WHERE lh_sample_uuid IS NULL AND cog_uk_id IS NOT NULL;
-- count: 19  max_date_tested: 2020-11-28 09:17:25
```

So there are 19 unmatched lighthouse samples.  I extracted the info for these:

```
SELECT id, lh_sample_uuid, cog_uk_id, plate_barcode
FROM lighthouse_sample
WHERE lh_sample_uuid IS NULL AND cog_uk_id IS NOT NULL;
```

Which gives:

```
13612442    NULL    BIRM-640DD     AP-rna-00151753
13807600    NULL    BIRM-640EC     AP-rna-00151893
17321145    NULL    BIRM-6C011     GLA058586R
15370055    NULL    BIRM-6C020     RNA437664
13763312    NULL    BIRM-6C03F     GLA041751R
13490323    NULL    BIRM-6C04E     AP-rna-00149697
11645042    NULL    BIRM-6C06C     AP-rna-00133344
6376770     NULL    BIRM-6C07B     002216727
13198865    NULL    BIRM-6C08A     AP-rna-00149568
9974504     NULL    NOTT-11D7FB    AP-rna-00130222
14635694    NULL    NOTT-11D807    AP-rna-00153348
14880512    NULL    NOTT-11D816    002328207
14906710    NULL    NOTT-11D825    AP-rna-00153944
14916120    NULL    NOTT-11D834    AP-rna-00155447
14982789    NULL    NOTT-11D843    002203027
15766485    NULL    NOTT-11D852    AP-rna-00154448
16533400    NULL    NOTT-11FAA5    AP-rna-00191372
14906686    NULL    NOTT-11FAB4    AP-rna-00153944
12304489    NULL    BIRM-6C05D     RNA427754
```

All of these, except the last one, do not have a matching row in the `stock_resource` table.  The last one does have rows in the table, but none of them match the `coordinate` from the `lighthouse_sample` table, so there is nothing to join and the `lh_sample_uuid` cannot be established using the above queries.

**Comment by KatyTaylor** [comment]
Hi Stuart
```
SELECT count(*), MAX(date_tested)
FROM lighthouse_sample
WHERE lh_sample_uuid IS NULL AND cog_uk_id IS NOT NULL;
```
Run  now on the prod snapshot gives `count: 194,748    MAX(date_tested): 2020-12-14 23:31:49`

So the extra ~300k that you're updating are ones that don't have a cog_uk_id in the lighthouse_sample table. 

I checked out why those 300k don't have the cog_uk_id and I think it's because they are not 'positive' samples and a previous migration didn't fill them in if they weren't positive - so I think that's ok.

All good and happy for you to go to production with this. I would send an email to mlwh-notices describing your plan, and give them at least 24 hours to get back to you before you run it.

Thanks!

**Comment by sdjmchattie** [comment]
This has been scheduled for deployment at 15:00 on 27th July 2021, unless anyone objects to my notification.
