### ISSUE TITLE
DPL-097 Sample / lighthouse_sample mismatch

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/unified_warehouse#262]
**Description**
Look into RT https://rt.sanger.ac.uk/SelfService/Display.html?id=726639

Summary:
1. Some lighthouse_sample records are still not linked via the uuid to their respective sample record, even though it looks like they should match based on root sample id, plate barcode and coordinate (see query provided for examples)
2. These records have mismatching results - lighthouse_sample.result does not match sample.phenotype
3. These records have filtered_positive = 0, therefore I would not expect them to have been sequenced (but they have been)

**Who the primary contacts are for this work**
Ian W

**Comment by KatyTaylor** [comment]
I think https://github.com/sanger/lighthouse/issues/361 is probably the cause of point 2.

**Comment by tc23sanger** [comment]
### Assuming that the column lighouse_sample.result contains the correct phenotype
```UPDATE lighthouse_sample SET sample.phenotype = lighthouse_sample.result;```

### With the phenotype fixed, update uuids with the following update

```
UPDATE lighthouse_sample
        INNER JOIN
    stock_resource ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
        AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
        INNER JOIN
    sample ON sample.id_sample_tmp = stock_resource.id_sample_tmp
        AND lighthouse_sample.root_sample_id = sample.description
        AND lighthouse_sample.result = sample.phenotype
SET 
    lighthouse_sample.lh_sample_uuid = sample.uuid_sample_lims
WHERE
    lighthouse_sample.lh_sample_uuid <> sample.uuid_sample_lims```

**Comment by KatyTaylor** [comment]
Hi @tc23sanger, I've just looked at your query above - 
On the surface of it, the approach seems good:
- first fix up the 'phenotype' column in the records where it was wrong due to [this bug](https://github.com/sanger/lighthouse/issues/361)
- then to run the uuid migration again to update any uuids that would have been missed previously due to mismatching result / phenotype.

I'm not sure how your first query will work though - doesn't it need a way to join between the `lighthouse_sample` and `sample` tables?

However...! I have just been thinking about this and I'm more confused than when I started. My initial hypothesis as to why these samples didn't have matching uuids was that it was because of the [phenotype bug](https://github.com/sanger/lighthouse/issues/361), as you know. However, I now think that's wrong because:
a) It looked like the phenotype bug only affected Beckman-cherrypicked samples - see [my comment here](https://github.com/sanger/lighthouse/issues/361#issuecomment-953037912)
b) Beckman-picked samples have always had their uuid set to match the lighthouse_sample uuid **on insertion**, so the uuids should match regardless of the phenotype / result. The migration mentioned in my first comment was actually just to set the uuids on the Sentinel-picked samples, not the Beckman ones.

So new hypotheses could be:
1. The uuids did initially match on these samples, but the data migration or subsequent data fixes overwrote them (due to the mismatching phenotypes?).
2. The uuids were not set correctly on insertion, for some unknown reason.
3. These are not actually Beckman samples, and the phenotype was set incorrectly because the code from the phenotype bug used to be used elsewhere too, or it was set incorrectly for a different reason.

I think it would help to figure out which cherrypicking method the samples in the RT ticket came from (sample manifest / manual, Sentinel, Beckman... can't be Biosero as that's too recent) - I can help you with this if needed.


On another note, because you said part 3 from my summary (filtered_positive) didn't make sense to you - the issue here was that some of the records from Ian's original RT ticket had the 'filtered_positive' field in lighthouse_sample table set to 0, but they had been sequenced anyway. This doesn't make sense because this field is the one used to specify that this sample should be cherrypicked - so if it is set to 0, why was the sample picked? Maybe it's not important to work this out, but I guess the concern would be that it could indicate a bug, which could still exist.

**Comment by KatyTaylor** [comment]
This is on hold for a while as Thiago has gone back to DPL-030

**Comment by andrewsparkes** [comment]
@KatyTaylor Possibly some samples are being selected for sequencing via the priority_samples route despite being filtered positive 0?
If that's the case you should be able to see the matching sample id in the Mongo priority_samples collection.

**Comment by sdjmchattie** [comment]
Having discussed the findings of last year with Katy, we can agree that there are 17,352 samples that have no matching lighthouse sample according to the UUID of the multi-lims warehouse sample.

- 8 of these have been addressed before as there is a second duplicate multi-lims warehouse sample for each that has a comment on it in SequenceScape explaining that it has a duplicate.
- All 17,344 of the remainder have a sample manifest ID associated with them, which means they didn't come through the lighthouse sample route to become inserted into the multi-lims warehouse.  These do not need to be modified.
- Except for 104 of them, for which a lighthouse sample can be found by looking for a matching root sample ID, plate barcode and labware coordinate.  Those 104 do match on those three criteria but have different UUIDs.  The reason for this is unclear, but they will now be checked to see whether the result is the same in both tables and to see whether we should be linking the UUID up for these or not.

**Comment by sdjmchattie** [comment]
Having spoken to Cristina A and Alan K, we agreed that no action is needed for the 8 samples that were sequenced twice and the 17,240 that were imported by sample manifest.  However the 104 lighthouse_sample entries split into two groups.  Those 95 where the result is the same in both the sample table and the lighthouse_sample table and then 9 which have different results in each table.  Alan believes he knows why this might have happened and will investigate those last 9, but the other 95 are going to have the UUID from the sample table copied into the lighthouse_sample table which means those samples, although also imported by sample manifest, will have a relevant lighthouse_sample assigned to them.

**Comment by sdjmchattie** [comment]
A SQL query has been run to update the 95 samples with the same result in both tables so that they share the UUID that was previously only on the sample table.  The remaining 9 samples of the 104 are being investigated further by Alan K to make a decision on what action to take.  I will add a log of the UUIDs as they were before the update applied here, when I have access to https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Project+Heron+Data+Fixes

**Comment by sdjmchattie** [comment]
The final 9 samples were checked by Alan K and he advised we should set the lighthouse sample entries to have a result of "Positive" as well as copy the UUIDs from the sample table.  This operation has been performed.

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
