### ISSUE TITLE
DPL-095 As a Product Lead (Sara S) I would a real time report of cherry picking across the Beckman & Biosero robots  so that Lab Users can track work in progress and managers can monitor throughput

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/unified_warehouse#264]
**User story**
As a Product Lead (Sara S) I would a real time report of cherry picking across the Beckman & Biosero robots so that Lab Users can track work in progress and managers can monitor throughput

**Who are the primary contacts for this story**
Scott T
Sara S

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The report should contain the same information provided by Scott T's existing Tableau report for the Beckman robots, but for all both Biosero & Beckman platforms in use
- [ ] The report should display the latest information in near real time (within a couple of minutes of a plate being picked)

**Dependencies**
This story is blocked by the following dependencies:

References
This story has a non-blocking relationship with:
- https://github.com/sanger/lighthouse/issues/381 DPL-047 Use stored procedure to retrieve destination plate information 

**Additional context**
Scott T has provided a near real-time Tableau reports of cherry picking by querying the DART database view _view_run_history_ 
The lab have found this invaluable in keeping track of work and quality assurance.
Sara S would like to have the report extended to incorporate data from the Biosero platform.

The DART database implementation is not tuned for performance (!) and the combination of this report and poor performance has caused the Beckman platform to stop operating  previously. Yann L. has improved the performance of the views in the DART DB and Sara's team will be carefully testing this in the week starting 2nd August, avoiding running the Tableau report and the Beckman robot process at the same time.  It would be great if Scott's report could get the information for both Beckman & Biosero from the MLWH and avoid any risk of overloading the DART DB.

The first step is to liaise with Scott and establish what information he needs for his report and work through possible options for providing this for both robot platforms.

**Comment by rl15** [comment]
Context
Tried stored procedures - did not work

Option b
Report from MLWH, using the events view. In discussion ith Andrew on 10th is suggesting events don't have all the information Scott T needs to run the Tableau report
Option c
Report from Cherrytrack - have one tableau report that can report for both Beckman and Biosero

**Comment by emrojo** [comment]
Actions:
- [ ] Check if changing the database isolation level for the tableau query could improve the performance problem.
- [ ] Create new views (view_heron_hitpicks and view_run_status) that handle 24 hour timeframe instead of current one and will be solely used for the Tableau reports.

Other options:
- [ ] Add a run start event to Beckman robot (not PSD)
- [ ] Automatic query of DART every x minutes to copy a delta of the data

**Comment by andrewsparkes** [comment]
Updates: 
Matt F has greatly improved the efficiency of Scotts Tableau dashboard queries for Beckman, so in theory we can try using that dashboard again in production and see if there is any affect on the running Beckman systems.
Scott also has a draft version of a dashboard running for Biosero. Not clear if this is production-ready.
Scott is currently on annual leave.

**Comment by KatyTaylor** [comment]
Sara confirmed today that this is an old story - Scott T provided everything they need with his Tableau reports. Closing issue & removing from project.
