### ISSUE TITLE
DPL-132 As a departing manager (Rich L) I would like to minimize the privileges on the mlwh_admin account as last action from Cherwell ticket

### ISSUE THREAD

**Issue by rl15** [sanger/unified_warehouse#287]
**User story**
As a departing manager (Rich L) I would like to minimize the privileges on the mlwh_admin account as last action from Cherwell ticket

**Who are the primary contacts for this story**
James G
Simon E (DSA)
Carl R (PAM/ Surveillance)
Tharini D (PAM/ Surveillance)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] minimize the privileges on the mlwh_admin account.

**Additional context**
See Cherwell ticket 309375

Simon E wrote (Tuesday, 7 September 2021 at 14:29) 

'While ideally the view definition should be altered to SQL SECURITY INVOKER, rather than SQL SECURITY DEFINER, as an immediate fix I’ve created a mlwh_admin account with appropriate privs.
So the issue is now fixed and that fix should persist across the weekly refreshes'

**Comment by harrietc52** [comment]
We're getting permission denied to RT ticket

**Comment by sdjmchattie** [comment]
Hi @rl15 .  Is there any more specific information could be added to this ticket?  Which databases does this need to apply to?  What are minimal privileges for this account?  Like @harrietc52 mentioned, neither of us can see the RT ticket.  Thanks :)

**Comment by stevieing** [comment]
RT729766
RT729771
