### ISSUE TITLE
DPL-067-4 MLWH records for compound sample (S)

### ISSUE THREAD

**Issue by harrietc52** [sanger/unified_warehouse#293]
**User story**
As a developer, we want to create a new table in the MLWH, linking the source sample to the pseudo sample (DPL-067-4)

**Who are the primary contacts for this story**
Harry
Eduardo
Katy

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Confirm with NPG
- [x] Creation of a new empty table
- [x] two columns, both integers, foreign keys to the samples table
- [x] Serialise the associations between compound and component samples in the messages broadcast by SequenceScape.
- [x] Deserialise the associations when received by MLWH, ensuring integrity of the data is preserved.

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
<img width="652" alt="Screenshot 2021-09-23 at 14 51 46" src="https://user-images.githubusercontent.com/11446617/134519567-4af39064-157b-4b3d-bed4-8e66be50a6bd.png">

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
