### ISSUE TITLE
DPL-234 - Are the MLWH events an hour behind BST?

### ISSUE THREAD

**Issue by stevieing** [sanger/unified_warehouse#298]
**Description**
Are the MLWH events an hour behind BST? There isn't a continuity between SS / MLWH and perhaps MLWH events

**Who the primary contacts are for this work**
Rich L

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
I suspect the times are being recorded correctly, just some in BST and some in UST. But even a discrepency like that would be good to fix.

**Comment by TWJW-SANGER** [comment]
Carl R does no think this is a problem.
Deprecated by the Product Owner.
