### ISSUE TITLE
DPL-nnn [BUG] study_users are generating duplicates [C=M, V=2]

### ISSUE THREAD

**Issue by emrojo** [sanger/unified_warehouse#307]
**Describe the bug**
When changing permissions for users with a study, the related MLWH table study_users is generating duplicates where the same user with the same role in the study appearse more than once

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page 'http://uat.sequencescape.psd.sanger.ac.uk/studies/<study_id>/collaborators'
2. Add and remove roles to users
3. Check the study_users table for that study

**Expected behaviour**
The study_users table should only have one record for each user with a role and study

**Screenshots**

![Screenshot 2021-10-26 at 11 44 00](https://user-images.githubusercontent.com/5426355/138862598-a931e6a5-ec79-45df-8aa1-40a029ccde78.png)

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by SujitDey2022** [comment]
Closing and moving to Done based on the comment shared in https://docs.google.com/spreadsheets/d/14Rh3Q1l_d1tqcxZy6wploMXQV_kSiBfamkaJzwgjt8E/edit#gid=0
