### ISSUE TITLE
DPL-269 [BUG] duplicate entries being created in the mlwh pac_bio_run table (C=M, V=5)

### ISSUE THREAD

**Issue by neilsycamore** [sanger/unified_warehouse#327]
There is an issue with duplicate entries being created in the mlwh pac_bio_run table (mainly from SS but also Traction). Di raised this Friday in RT742182  latest examples are for batch/run:
89882
89269
89266
89645
89256
89276
89273
(and TRACTION-RUN-70)
On Friday the pacbio batches that I touched individually resent the message and corrected the entries. When I tried this in a bulk transaction not all did

**Comment by JamesGlover** [comment]
Adding unique index constraints to the MLWH helped avoid similar issues in the Iseq-flowcell tables. There the problem was duplicate (or near-duplicate) messages being processed in parallel by two different consumers. Its likely that we have a similar problem here, although I'm surprised that we're seeing such an issue from traction, as message broadcast is a lot more manual there.

**Comment by stevieing** [comment]
The thing I am puzzled by is why this has just started happening??

**Comment by JamesGlover** [comment]
Good question, and the RT ticket puts it before the latest WH release. Do we know *when* the issue started?

**Comment by JamesGlover** [comment]
Complication: You can't just add a constraint on, say `id_pacbio_run_lims,well_label,tag_identifier_tag2_identifier` as single indexed aliquots have a tag2_identifier of NULL, and when it comes to uniqueness constraints `NULL != NULL`. This is why untagged aliquots in SS have a tag_id of -1.

I have had some luck trialing and adding index constraints on virtual columns This allows keeping the raw column as NULL, but then having an indexed virtual column with something like IFNULL(-1)

**Comment by neilsycamore** [comment]
> Good question, and the RT ticket puts it before the latest WH release. Do we know _when_ the issue started?

Ticket created Thurs 27 @16:15. Di says it was first noticed 1-2 days before.

**Comment by JamesGlover** [comment]
Bit of investigation:

1) 1606 batches with issues at start of investigation. Checked and found Neil's rebroadcast would have sent duplicate messages, when these were resent the numbers dropped down to 164 batches.
2) These bad batches all have multiple requests into the target asset, as the message itself ends up containing duplicate records for each sample. This is as the message generator does:
```
with_nested_has_many_association(:requests_as_target, as: 'samples')
```
I'm not quite sure why we're ending up with multiple requests pointing at the same well, I've forgotten a lot of details about how the PacBio pipeline works. I do recall something about lanes of sequencing required, and then cancelling some of these based on yields. I wouldn't be surprised if this was interacting badly with multiplexing. However, given I've got another branch in place to delete all this code, its probably only worth fixing up the message generation to exclude anything with the same source asset.

That still leaves the need to update the database to handle duplicate messages. The aforementioned index constraints should work. I *think* it will even trigger a re-processing of the failed message, which should either result in it being ignored (if it is older or the same age as the existing message) or updated (if its newer)

**Comment by ces** [comment]
> > Good question, and the RT ticket puts it before the latest WH release. Do we know _when_ the issue started?
> 
> Ticket created Thurs 27 @16:15. Di says it was first noticed 1-2 days before.

Yes many many months before e.g. mentioned in RT #731334 (12/09/21). Lovely to hear this is being worked on.

**Comment by emrojo** [comment]
Also this pull request: https://github.com/sanger/sequencescape/pull/3555
