### ISSUE TITLE
DPL-437-5 Create repo for SQL queries, and add billing/TAT-WOW queries

### ISSUE THREAD

**Issue by harrietc52** [sanger/unified_warehouse#410]
**User story**
As a developer, we would like there to be a GitHub repository where queries can be added to an organised GitHub repo. The scope of this story (MVP) involves only SQL queries.

In the future, it could be flexible and add Rails/ other documentation/ data exports etc (similar to the GitLab [data-patch-archive ](https://gitlab.internal.sanger.ac.uk/psd/data-patch-archive )where templates are used to generate different types of documentation).  But this is not part of the initial MVP story.

This will be used to add the billing query, along with other queries such as TAT WOW queries. 

**Who are the primary contacts for this story**
@harrietc52 
@KatyTaylor 

**Who is the nominated tester for UAT**
@harrietc52 

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Create a GitHub repo
- [ ] Add the Billing Query to the repo (full query and with batch)
- [ ] Add TAT-WOW queries to the repo (currently in unified warehouse repo)

Future:
- [ ] Compile a list of documentation formats to support, such as SQL query, Ruby on Rails commands etc (**not MVP**)
- [ ] Create a template to build the various documentations (**not MVP**)

References
This story has a non-blocking relationship with:
- This is a spin-out story from https://github.com/sanger/unified_warehouse/issues/386

**Additional context**

**Comment by harrietc52** [comment]
@TWJW-SANGER

**Comment by TWJW-SANGER** [comment]
Just to check - did @KatyTaylor create a repo for this already? I can't find one so possibly not.

Anyway assuming she didn't I think we do need something like this.

But I would be tempted to narrow the scope.

I don't believe there are any Ruby / Rails scripts to add at the moment? Could we just support SQL for now?

I'm also not entirely sure about the "build various documentation task" or "Create a template to build the various documentations"? 
Could the billing report SQL serve as template for others to follow w/o requiring any more complex for now?

**Comment by harrietc52** [comment]
@TWJW-SANGER 

Hi, nope I don't think anything has been done on this story. 
And yes, I agree it could be a really simple MVP implementation!

**Comment by SujitDey2022** [comment]
@harrietc52 please can you help confirm if we need this story or if we can archive the same.

**Comment by SujitDey2022** [comment]
@harrietc52 please can you help confirm if we need this story or if we can archive the same?

**Comment by harrietc52** [comment]
@SujitDey2022 Sorry, this can be deprecated (have discussed with Tom)

**Comment by SujitDey2022** [comment]
Thanks for the update @harrietc52
