### ISSUE TITLE
DPL-437-6 Billing report: Test Tableau report

### ISSUE THREAD

**Issue by harrietc52** [sanger/unified_warehouse#413]
**User story**
A Matt F, to display the billing report in Tableau, I would like to know how to best display the read lengths in the report. 

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Who is the nominated tester for UAT**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Confirm `read_length` ranges 
- [ ] Show Billing report with read lengths from stored proc
- [ ] Confirm if Rich R would like read lengths to be displayed in respective columns
- [ ] If so, confirm what ranges the read lengths should be grouped by. e.g. read length of 151 should map to 150. 

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/unified_warehouse/issues/412

References
This story has a non-blocking relationship with:
- This is a spin-out story from https://github.com/sanger/unified_warehouse/issues/386

**Additional context**

**Comment by harrietc52** [comment]
@TWJW-SANGER

**Comment by TWJW-SANGER** [comment]
I agree the actual work here sits with Matt F rather than PSD - happy to close.
