### ISSUE TITLE
DPL-734 Edit Billing query groupings (C=S, V=3)

### ISSUE THREAD

**Issue by harrietc52** [sanger/unified_warehouse#485]
**User story**
As Rich R, I would like to edit the groupings on the Billing report query, to have Batch ID and Lane Positions unique per record. Currently these are grouped, which makes investigation harder.  

To the query provided [here](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Automating+Billing+Report#AutomatingBillingReport-SQL), I would like to add the below fields to the final grouping.  

Fields:
Lane Position (`iseq_run_lane_metrics.position`)
Batch ID (`iseq_flowcell.id_flowcell_lims`) 

e.g.
```
   <other groupings>
    , iseq_flowcell.id_flowcell_lims -- batch_id
    , iseq_run_lane_metrics.position -- lane_position
```

Expected data:
In the example spreadsheet ([RT #776721](https://rt.sanger.ac.uk/SelfService/Display.html?id=776721&results=284451a244b9ca50b10e33f5c7b0b191)), line 9 (highlighted) shouldn’t be rolled to 1 line. It should be represented over at least 12 lines as there are 3 batched all with 4 lane positions ( 3 x 4 = 12). This spreadsheet was generated with dates 23/02/23 - 27/03/23 inclusive.

For example, when you run the query with dates `CALL billing_report_stored_proc('2023-02-23 00:00:00', '2023-03-27 23:59:59');`, previously this would have returned 2 lines for study "Placental genomics" (one `XP`, one `No XP`). After making this change, the same study should return 12 lines for `XP`, and 12 lines for `No XP`.

**Who are the primary contacts for this story**
Rich R
@harrietc52 
@andrewsparkes 

**Who is the nominated tester for UAT**
Rich R
Matt Francis

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Email Rich R to say this story has been picked up. 
- [x] If any example files have been provided, ask for the exact dates used, so these can be used in the query when testing and comparing. **A: 23/02/23 - 27/03/23 inclusive.**
- [x] Email Matt F to say there will be some updates to the Stored procedure coming soon. 
- [x] Copy the latest stored procedure creation from the Conf doc [here](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Automating+Billing+Report#AutomatingBillingReport-SQL)
- [x] Test the unedited creating and running the stored procedure in MLWH Training (ADMIN role is required) [commands here](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Automating+Billing+Report#AutomatingBillingReport-CallingtheStoredProcedure)
- [x] Add the two fields, as specified above, to the final grouping
- [x] Scan the "Expected data" as mentioned above, to check the data is as expected
- [x] Test again creating and running the stored procedure in MLWH Training, with the added fields to the grouping (ADMIN role). The number of rows should be more than the ones provided in these comments [here](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Automating+Billing+Report#AutomatingBillingReport-CallingtheStoredProcedure)
- [x] When happy, remove the existing Stored Proc from MLWH Prod (command at the bottom of [here](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Automating+Billing+Report#AutomatingBillingReport-SQL)) (ADMIN role)
- [x] Replace with the updated Stored Proc (ADMIN role)
- [x] Update confluence page [here](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Automating+Billing+Report#AutomatingBillingReport) with the latest query and anything else relevant to the updated stored procedure (e.g. Grouping section).
- [x] Send the updated query to Matt F
- [x] Matt to update the Tableau view [here](https://globalreporting.internal.sanger.ac.uk/#/views/NewBilling/SequencingBilling?:origin=viz_share_link&:iid=1) 
- [x] Test the view has the new data (Steps: click anywhere in the view, click `Download` in the top R, select `Data`. 
- [x] Update Rich R when the Tableau view has been updated

**Additional context**

**Comment by SujitDey2022** [comment]
![image](https://github.com/sanger/unified_warehouse/assets/115623404/c9c3fc77-9fd8-4be1-95ff-213f8b55130c)

**Comment by SujitDey2022** [comment]
![image](https://github.com/sanger/unified_warehouse/assets/115623404/6909b9e5-222d-4905-896e-2dc5ac4f93bb)

**Comment by harrietc52** [comment]
Rich is out of office until 04/08/23 (so going to be hard to test!)

**Comment by harrietc52** [comment]
```
-- old grouping
-- 23/02/23 -> 27/03/23 =  183 rows
-- Placental genomics 2 lines (1 for XP, 1 for No XP)

-- new grouping
-- 23/02/23 -> 27/03/23 =  646 rows
-- Placental genomics 20 lines (8 for XP, 12 for No XP)
-- 3 batches, with 4 lanes each, for No XP
-- 2 batches, with 4 lanes each, for XP (maybe there is a batch missing)
```
