### ISSUE TITLE
DPL-1049 Update comment for iseq_flowcell entity_type

### ISSUE THREAD

**Issue by neilsycamore** [sanger/unified_warehouse#579]
As a member of NPG (Marina G)  I would like the comment for the entity_type column updated by removing the reference to "pool". The semantics of the iseq_flowcell table does not allow for pool records.

**Who are the primary contacts for this story**
Marina G, Keith J 

References
Raised in [RT795182](https://rt.sanger.ac.uk/Ticket/Display.html?id=795182)

mysql> show create table iseq_flowcell;

| iseq_flowcell | CREATE TABLE `iseq_flowcell` (
...
`entity_type` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Lane type: library, pool, library_control, library_indexed, library_indexed_spike',
...
) ENGINE=InnoDB AUTO_INCREMENT=12366252 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |

mysql> select distinct entity_type from iseq_flowcell;;
+-----------------------+
| entity_type           |
+-----------------------+
| library               |
| library_control       |
| library_indexed       |
| library_indexed_spike |
+-----------------------+

**Comment by dasunpubudumal** [comment]
Hi @neilsycamore, the following SQL statement can be used to update the corresponding comment in the table:

```
ALTER TABLE <database>.iseq_flowcell MODIFY COLUMN entity_type varchar(30) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Lane type: library, library_control, library_indexed, library_indexed_spike';
```

I've already executed this in Which database `mlwhd_mlwarehouse_devdata`. Shall I execute it for `mlwhd_mlwarehouse` as well?

**Comment by dasunpubudumal** [comment]
**Deployment procedure:**

- [ ] Check the `iseq_flowcell` table’s `entity_type` attribute’s comment and verify that it has got a “pool” keyword.
- [ ] Note down some data with their primary keys. These will be used for later verification after the fix has been applied.
- [ ] Take a screenshot for further clarity.
- [ ] Apply the deployment command.
- [ ] Verify the “pool” keyword is not there in the `entity_type` column comment of the `iseq_flowcell` table.
