### ISSUE TITLE
GPL-418 - As a developer I need to able to multiplex ONT runs

### ISSUE THREAD

**Issue by stevieing** [sanger/unified_warehouse#96]
**User story**
As NPG I need ONT to support multiplexing by adding tagging information to the oseq_flowcell table. ONT protocols now allow multiple tags (e.g. 24 native barcodes plus 96 PCR barcodes to give 2,304 plex) so we should consider having space for additional tag information.

**Who the primary contacts are for this story**
Keith James

**Acceptance criteria**
To be considered successful the solution must allow:
1. The following fields need to be available in the oseq_flowcell table:
- tag_identifier
- tag_sequence
- tag_set_id_lims
- tag_set_name

2. The following fields should also be available in the oseq_flowcell table:
- tag2_set_id_lims	LIMs-specific identifier of the tag set
- tag2_set_name		WTSI-wide tag set name
- tag2_identifier		The position of tag within the tag group
- tag2_sequence		Tag sequence

**Additional context**

**Comment by stevieing** [comment]
Make requested_data_type and pipeline_id_lims nullable
for instrument name it is GXB02004

**Comment by harrietc52** [comment]
requested_data_type => base calls/ raw data. not nullable (make nullable)
pipeline_id_lims

**Comment by stevieing** [comment]
Try and create a single message for each run or flowcell. This would involve making changes to traction service to create a single message and for the warehouse to accept a single message.
